### ISSUE TITLE
newrelic_agent.log untracked file keeps being created

### ISSUE THREAD

**Issue by brianjmurrell** [TeamCodeStream/codestream#1044]
Issue Type: <b>Bug</b>

I keep removing an untracked file in my repos called newrelic_agent.log only for it to show up a short time later.

I have no idea what this log is or what is producing it but it's really annoying to randomly have untracked files show up and get added to git commits before they are noticed.

The file's contents are:

```json
{"v":0,"level":30,"name":"newrelic","hostname":"laptop.example.com","pid":406125,"time":"2022-06-20T17:28:20.223Z","msg":"Unable to find configuration file. If a configuration file is desired (common for non-containerized environments), a base configuration file can be copied from 13585 and renamed to \"newrelic.js\" in the directory from which you will start your application. Attempting to start agent using environment variables."}
{"v":0,"level":30,"name":"newrelic","hostname":"laptop.example.com","pid":406125,"time":"2022-06-20T17:28:20.235Z","msg":"Using New Relic for Node.js. Agent version: 8.9.1; Node version: v16.13.0."}
{"v":0,"level":30,"name":"newrelic","hostname":"laptop.example.com","pid":406125,"time":"2022-06-20T17:28:20.380Z","msg":"Using LegacyContextManager"}
{"v":0,"level":50,"name":"newrelic","hostname":"laptop.example.com","pid":406125,"time":"2022-06-20T17:28:20.381Z","msg":"New Relic requires that you name this application!\nSet app_name in your newrelic.js file or set environment variable\nNEW_RELIC_APP_NAME. Not starting!"}
{"v":0,"level":50,"name":"newrelic","hostname":"laptop.example.com","pid":406125,"time":"2022-06-20T17:28:20.382Z","msg":"New Relic for Node.js was unable to bootstrap itself due to an error:","stack":"Error: New Relic requires that you name this application!\nSet app_name in your newrelic.js file or set environment variable\nNEW_RELIC_APP_NAME. Not starting!\n    at /home/brian/.vscode/extensions/codestream.codestream-13.0.0/dist/agent.js:2:1192885\n    at /home/brian/.vscode/extensions/codestream.codestream-13.0.0/dist/agent.js:2:1193234\n    at Object.82383 (/home/brian/.vscode/extensions/codestream.codestream-13.0.0/dist/agent.js:2:1194154)\n    at __webpack_require__ (/home/brian/.vscode/extensions/codestream.codestream-13.0.0/dist/agent.js:59:1292735)\n    at Object.72689 (/home/brian/.vscode/extensions/codestream.codestream-13.0.0/dist/agent.js:2:2246371)\n    at __webpack_require__ (/home/brian/.vscode/extensions/codestream.codestream-13.0.0/dist/agent.js:59:1292735)\n    at /home/brian/.vscode/extensions/codestream.codestream-13.0.0/dist/agent.js:59:1293717\n    at Object.<anonymous> (/home/brian/.vscode/extensions/codestream.codestream-13.0.0/dist/agent.js:59:1293767)\n    at Module._compile (node:internal/modules/cjs/loader:1163:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)","message":"New Relic requires that you name this application!\nSet app_name in your newrelic.js file or set environment variable\nNEW_RELIC_APP_NAME. Not starting!"}
```

Extension version: 13.1.1
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.18.7-200.fc36.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2722)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|62.48GB (18.43GB free)|
|Process Argv|--unity-launch --crash-reporter-id d33a766b-28e9-45e5-942d-3a9085ddc0c0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdf:30486550

```

</details>

**Comment by brianjmurrell** [comment]
Code collected the extension version during the initial report:

> Extension version: 13.1.1

Which does indeed match what the UI reports:

![image](https://user-images.githubusercontent.com/559317/177558158-7884813b-d376-47a8-b686-d12d6244a9f4.png)

**Comment by bcanzanella** [comment]
Thanks for that additional info @brianjmurrell . I've tried this with 13.1.1 and I'm unable to reproduce. Could I trouble you to send over your `CodeStream` _and_ `CodeStream (Agent)` logs to me? The instructions can be found here: https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/ (Note: they only mention `CodeStream (Agent)` logs but we will need both  `CodeStream` _and_ `CodeStream (Agent)` here.

Please email them to me at brian@codestream.com. Thanks.
