### ISSUE TITLE
JsonRpcException on startup. codestream cannot load

### ISSUE THREAD

**Issue by GeniusV** [TeamCodeStream/codestream#1075]
Codestream throws `org.eclipse.lsp4j.jsonrpc.JsonRpcException` on startup and stuck on loading. 
```
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: The pipe is being closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at com.sun.proxy.$Proxy94.initialize(Unknown Source)
	at com.codestream.agent.AgentService.initAgent(AgentService.kt:170)
	at com.codestream.agent.AgentService.initAgent$default(AgentService.kt:152)
	at com.codestream.agent.AgentService$1.invokeSuspend(AgentService.kt:141)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: The pipe is being closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 12 more
```

![Image 6](https://user-images.githubusercontent.com/13480362/180957365-29899828-50ef-4b57-9cb0-1e1b0452651e.png)

- IntelliJ IDEA 2022.1.3 (Ultimate Edition)
- codestream 13.2.0+239

Please help advice what should I do, thanks.

**Comment by planteater** [comment]
@GeniusV - Could I trouble you for a complete log file? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can email that to me directly at support@codestream.com. 

Also, what OS are you on? Thanks!

**Comment by GeniusV** [comment]
@planteater Sorry for the late reply. Just being busy these days. Log file was sent by mail and my os is windows 7. Thank you for your help.

**Comment by planteater** [comment]
@GeniusV - From my dev team..

"They are using WIN32 (Windows 7, EOL 2020), for which we don't ship a Node.js binary. I've made a change to fallback to the system-installed node in that case. They should install Node.js and make it available in the system path. We cannot guarantee it will work though."

The release with the fallback should go out tomorrow, but I'll update you here once it happens. Usually takes 24 hours for JetBrains to approve the release.

**Comment by planteater** [comment]
Release with the fallback, v13.4, is now available.
