### ISSUE TITLE
JetBrains :: Plugin Crashes When Launched

### ISSUE THREAD

**Issue by lots0logs** [TeamCodeStream/CodeStream#119]
**Describe the bug**
When starting PHPStorm the Codestream plugin crashes with the following error:
```
java.lang.NoSuchMethodError: 'void com.intellij.credentialStore.CredentialAttributes.<init>(java.lang.String, java.lang.String, java.lang.Class, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at com.codestream.settings.SettingsService.getCredentialAttributes(SettingsService.kt:171)
	at com.codestream.authentication.AuthenticationService.autoSignIn(AuthenticationService.kt:57)
	at com.codestream.agent.AgentService.initAgent(AgentService.kt:108)
	at com.codestream.agent.AgentService$initAgent$1.invokeSuspend(AgentService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**System Info (please complete the following information):**
```
=== About ===
Build version: PhpStorm 2019.2.3 RC Build #PS-192.6817.12 September 18, 2019
Java version: 11.0.4+10-b304.69amd64
Operating System: Linux (5.2.14-arch2-1-arch, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 24
Used memory: 781Mb 
Free memory: 427Mb 
Total memory: 1208Mb 
Maximum available memory: 1979Mb

=== Displays ===
Displays: 
Display 0: 2560x1440; scale: 1.00

=== Plugins ===
Custom plugins: [String Manipulation (7.2.182.000.3), Thursday (0.1.2), Switch Component files (1.0), Git Branch Manager (1.0.4), Nord (0.8.1), Material Theme UI (4.5.1), Codealike (1.5.0.29), CoderMirror (1.2.3), CodeStream (2.1.3+11), Ideolog (192.0.12.0), Completion Stats Collector (0.1.9), Gray Theme (1.1.1), React snippets (1.1.0), JS Toolbox (1.9), One Dark theme (3.0.0), Git Branch Cleaner (1.1.2), Gradianto (3.5), Atom OneDark Theme (1.6), One Dark Native (1.4), CPU Usage Indicator (1.8), Case conversion (0.5.1), .ignore (3.2.2.192), Makefile support (1.6.1), Code::Stats (1.0.6), CodeGlance (1.5.4), HashiCorp Terraform / HCL language support (0.7.6), Find Pull Request (1.5.0), Php Inspections (EA Extended) (3.0.16.1), deep-assoc-completion (2019.09.18.002), ESLint (1.0.36), silkworm (1.0.7), Extra Icons (1.8.0.183), GitToolBox (192.3.0)]
Disabled plugins:[IntelliPort (1.0), Configuration Script (192.6817.12), Theme Collection (0.8), Interesting Theme (1.3), BashSupport (1.7.10.192), Python (2019.1.191.6183.20), jsondiff (0.2), Angular and AngularJS (192.6817.12)]
```

**Log Files**
[phpstorm-logs-20190919-132250.zip](https://github.com/TeamCodeStream/CodeStream/files/3632669/phpstorm-logs-20190919-132250.zip)

**Comment by marcelofarias** [comment]
Thanks for the report - we are working on it. In the meanwhile, it should work on PHPStorm version 2019.2.2.

**Comment by marcelofarias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JetBrains :: Plugin Crashes When Launched](https://trello.com/c/NDMMOgHd/2344-jetbrains-plugin-crashes-when-launched)

**Comment by marcelofarias** [comment]
@lots0logs It looks like there's an issue with PHPStorm 2019.2.3 RC build 192.6817.12. We have reported it here: https://youtrack.jetbrains.com/issue/WI-48781

I just checked PhpStorm 2019.2.2 and 2019.3 EAP. If that's an option for you, CodeStream should work fine on both.
