### ISSUE TITLE
java.lang.Throwable: class com.intellij.openapi.module.ModuleManager it is a service, use getService instead of getComponent

### ISSUE THREAD

**Issue by Novocastrian** [TeamCodeStream/codestream#1198]
- IDE Version: PHPStorm 2022.3 EAP Build #PS-223.4884.75, built on September 23, 2022
- OS Version: Windows 11 Pro

Steps to Reproduce:

1. Install the latest non-EAP PHPStorm build
2. Install the codestream plugin
3. Install the latest EAP PHPStorm build
4. Launch it. You will see an error popup, with this error:
![image](https://user-images.githubusercontent.com/4601813/193175646-5e7700fc-4d2e-4854-930a-8df3ab44c39c.png)
![image](https://user-images.githubusercontent.com/4601813/193175633-73ef2640-d436-4ae1-b216-15b752e7a1f7.png)

`java.lang.Throwable: class com.intellij.openapi.module.ModuleManager it is a service, use getService instead of getComponent
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:612)
	at com.codestream.extensions.ProjectKt.getWorkspaceFolders(Project.kt:17)
	at com.codestream.agent.AgentService.initializationOptions(AgentService.kt:442)
	at com.codestream.agent.AgentService.getInitializeParams(AgentService.kt:414)
	at com.codestream.agent.AgentService.initAgent(AgentService.kt:175)
	at com.codestream.agent.AgentService.initAgent$default(AgentService.kt:155)
	at com.codestream.agent.AgentService$1.invokeSuspend(AgentService.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

This results in the plugin not running - as evidenced by no in-line git blame.

**Comment by planteater** [comment]
Thanks for the heads up @Novocastrian! We've got a fix going out in a release later this week.

**Comment by planteater** [comment]
@Novocastrian - This issue has been fixed in version 14.3 of the CodeStream extension.
