### ISSUE TITLE
Jetbrains :: CodeStream Panel Empty. Slack API Error Found In Log.

### ISSUE THREAD

**Issue by lots0logs** [TeamCodeStream/CodeStream#124]
**Describe the bug**
When I started PHPStorm today the CodeStream panel was completely empty and there was no way to do anything via the UI and no indication of what could be wrong. There is a Slack API error in the log though:

```
2019-10-14 16:50:29,987 [  14431]   WARN - agent.CodeStreamLanguageClient - [2019-10-14 21:50:29:986] [db] SlackApiProvider.slackApiCall users.prefs.get() {"ok":false,"error":"missing_scope","needed":"read","provided":"identify,channels:history,groups:history,im:history,mpim:history,channels:read,groups:read,im:read,mpim:read,users:read,users:read.email,users.profile:read,channels:write,chat:write:user,groups:write,im:write,mpim:write,reactions:write","response_metadata":{"scopes":["identify","channels:history","groups:history","im:history","mpim:history","channels:read","groups:read","im:read","mpim:read","users:read","users:read.email","users.profile:read","channels:write","chat:write:user","groups:write","im:write","mpim:write","reactions:write"],"acceptedScopes":["read"]}}
Error: An API error occurred: missing_scope
Error: An API error occurred: missing_scope
    at Object.t.platformErrorFromResult (/snapshot/dist/agent.js:0:0)
    at WebClient.apiCall (/snapshot/dist/agent.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
2019-10-14 16:50:29,987 [  14431]   WARN - agent.CodeStreamLanguageClient - [2019-10-14 21:50:29:986] [db] SlackApiProvider.slackApiCall users.prefs.get() — failed • 241 ms
Error: An API error occurred: missing_scope
Error: An API error occurred: missing_scope
    at Object.t.platformErrorFromResult (/snapshot/dist/agent.js:0:0)
    at WebClient.apiCall (/snapshot/dist/agent.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
2019-10-14 16:50:29,987 [  14431]   WARN - agent.CodeStreamLanguageClient - [2019-10-14 21:50:29:986] Object.t.platformErrorFromResult
Error: An API error occurred: missing_scope
Error: An API error occurred: missing_scope
    at Object.t.platformErrorFromResult (/snapshot/dist/agent.js:0:0)
    at WebClient.apiCall (/snapshot/dist/agent.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
```

**System Info (please complete the following information):**
```
=== About ===
Build version: PhpStorm 2019.2.3 Build #PS-192.6817.20 September 25, 2019
Java version: 11.0.4+10-b304.69amd64
Operating System: Linux (5.3.5-arch1-1-arch, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 24
Used memory: 942Mb 
Free memory: 865Mb 
Total memory: 1808Mb 
Maximum available memory: 1979Mb

=== Displays ===
Displays: 
Display 0: 2560x1440; scale: 1.00

=== Plugins ===
Custom plugins: [String Manipulation (7.2.182.000.3), Thursday (0.1.2), Switch Component files (1.0), Nord (0.8.1), Material Theme UI (4.5.1), Codealike (1.5.0.29), CodeStream (4.0.1+18), Ideolog (192.0.12.0), Completion Stats Collector (0.1.9), Gray Theme (1.1.1), React snippets (1.1.0), JS Toolbox (1.9), One Dark theme (3.0.0), Gradianto (3.6), Atom OneDark Theme (1.6), One Dark Native (1.4), Case conversion (0.5.1), .ignore (3.2.2.192), Makefile support (1.6.1), Code::Stats (1.0.6), CodeGlance (1.5.4), HashiCorp Terraform / HCL language support (0.7.7), Find Pull Request (1.5.0), Php Inspections (EA Extended) (3.0.16.2), deep-assoc-completion (2019.10.07.001), ESLint (1.0.36), silkworm (1.0.7), Extra Icons (1.11.0.183)]
Disabled plugins:[IntelliPort (1.0), Configuration Script (192.6817.20), Theme Collection (0.8), Interesting Theme (1.3), BashSupport (1.7.10.192), Python (2019.1.191.6183.20), jsondiff (0.2), Angular and AngularJS (192.6817.20)]
```

**Log Files**
[phpstorm-logs-20191014-170139.zip](https://github.com/TeamCodeStream/CodeStream/files/3726569/phpstorm-logs-20191014-170139.zip)

**Comment by lots0logs** [comment]
I got it working again by disabling Automatic Sign In in the settings and then restarting PHPStorm. I was then able to sign in with Slack using the UI and that seems to have resolved the problem.

**Comment by marcelofarias** [comment]
Thanks! The logs you've shared will help us prevent this problem in the future. Alternatively, you could also use the _CodesStream: Sign Out_ action. Use `Cmd + Shift + A` on Mac to open the actions list on any JetBrains IDE.

**Comment by marcelofarias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GH124 - Blank CS panel when Slack RT scopes are missing](https://trello.com/c/5XTl7QCy/2490-gh124-blank-cs-panel-when-slack-rt-scopes-are-missing)

**Comment by Velaseriat** [comment]
I'll mention that I ran into the same issue. Thank you for the workaround.
