### ISSUE TITLE
Slack integration error

### ISSUE THREAD

**Issue by mateuszzw** [TeamCodeStream/CodeStream#126]
Hi,

After linking codestream to a fresh slack team, I receive the error listed below every time I try to create a new comment.

Is it bound to the fact that I have a user with the same email address in different slack teams?

2019-10-28T08:48:47.278
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at com.codestream.agent.AgentService.documentMarkers(AgentService.kt:264)
	at com.codestream.editor.EditorService.getDocumentMarkers(EditorService.kt:215)
	at com.codestream.editor.EditorService$updateMarkers$2.invokeSuspend(EditorService.kt:195)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
	... 9 more

**Comment by planteater** [comment]
I’ll dig into this ASAP. I’ll need your email address though. If you’d prefer not to post it here, you can send it to support@codestream.com. Thanks!

**Comment by planteater** [comment]
Per separate conversation, issue turned out to be the fact that we don't yet support Bitbucket on-prem (which is definitely on our roadmap).
