### ISSUE TITLE
Opening Codestream panel in PHPStorm gives "An unexpected error has occurred." while loading

### ISSUE THREAD

**Issue by veloxy** [TeamCodeStream/codestream#1269]
- IDE Version: PhpStorm 2022.2.3 Build #PS-222.4345.15, built on October 5, 2022
- OS Version: MacOS Montary 12.3.1 (21E258)

Steps to Reproduce:

1. Installed the plugin
2. Opened the panel and Logged in through Github
3. Panel refreshes and before it's fully loaded (i can briefly see some contents) would give following message:

```
An unexpected error has occurred.

Click here to reload.

If the problem persists please contact [codestream@newrelic.com](mailto:codestream@newrelic.com)
```

logs:

```

2022-11-17 15:14:34,086 [ 305828]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:14:34:085] [2aa] NewRelicProvider.getFileLevelTelemetry
2022-11-17 15:14:34,086 [ 305828]   WARN - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:14:34:086] NR: getFileLevelTelemetry: not connected — {"request":{"fileUri":"file:///<redacted>/Message/Changes/Items/ReplaceItemsMessage.php","languageId":"php","locator":{"namespaces":["<redacted>\\Message\\Changes\\Items","<redacted>\\Message\\Changes\\Items\\ReplaceItemsMessage"]},"resetCache":false,"options":{"includeThroughput":true,"includeAverageDuration":true,"includeErrorRate":true}},"zetails":{}}
2022-11-17 15:14:34,086 [ 305828]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:14:34:086] [2aa] NewRelicProvider.getFileLevelTelemetry completed • 1 ms
2022-11-17 15:14:34,087 [ 305829]   INFO - #c.c.c.CLMEditorManager - Not updating CLM metrics due to error NOT_CONNECTED
2022-11-17 15:15:09,133 [ 340875]   INFO - #c.c.w.WebViewService - Loading WebView
2022-11-17 15:15:09,387 [ 341129]   INFO - #c.c.w.JBCefWebView - Router connected
2022-11-17 15:15:09,391 [ 341133]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:391] [2ac] CodeStreamApiProvider.getUnreads
2022-11-17 15:15:09,392 [ 341134]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:392] [2ad] CodeStreamApiProvider.getPreferences
2022-11-17 15:15:09,395 [ 341137]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:395] [2ac] CodeStreamApiProvider.getUnreads completed • 3 ms
2022-11-17 15:15:09,712 [ 341454]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:712] API(fb7ef199-6394-4967-8af8-6bc83e4fd9d9): Completed GET /preferences • 319 ms
2022-11-17 15:15:09,712 [ 341454]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:712] [2ad] CodeStreamApiProvider.getPreferences completed • 320 ms
2022-11-17 15:15:09,718 [ 341460]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:718] Verifying API server connectivity
2022-11-17 15:15:09,760 [ 341502]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:760] GIT: Running(undefined): git config --get user.email
2022-11-17 15:15:09,766 [ 341508]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:766] [2af] ScmManager.getFileInfo
2022-11-17 15:15:09,774 [ 341516]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:774] GIT: Running(/<redacted>/Message/Changes/Items): git rev-parse --abbrev-ref HEAD
2022-11-17 15:15:09,780 [ 341522]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:779] [2b0] ScmManager.getFileInfo
2022-11-17 15:15:09,781 [ 341523]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:780] GIT: Awaiting(/<redacted>/Message/Changes/Items): git rev-parse --abbrev-ref HEAD
2022-11-17 15:15:09,781 [ 341523]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:780] [2b1] ScmManager.getFileInfo
2022-11-17 15:15:09,781 [ 341523]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:780] GIT: Awaiting(/<redacted>/Message/Changes/Items): git rev-parse --abbrev-ref HEAD
2022-11-17 15:15:09,793 [ 341535]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:792] [2b4] ReviewsManager.get
2022-11-17 15:15:09,793 [ 341535]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:793] [2b4] ReviewsManager.get completed • 0 ms
2022-11-17 15:15:09,793 [ 341535]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:793] [2b5] ReviewsManager.get
2022-11-17 15:15:09,793 [ 341535]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:793] [2b5] ReviewsManager.get completed • 0 ms
2022-11-17 15:15:09,793 [ 341535]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:793] GIT: Completed(/<redacted>/Message/Changes/Items): git rev-parse --abbrev-ref HEAD in 19 ms
2022-11-17 15:15:09,793 [ 341535]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:793] GIT: Completed(/<redacted>/Message/Changes/Items): git rev-parse --abbrev-ref HEAD in 13 ms
2022-11-17 15:15:09,793 [ 341535]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:793] GIT: Completed(/<redacted>/Message/Changes/Items): git rev-parse --abbrev-ref HEAD in 12 ms
2022-11-17 15:15:09,797 [ 341539]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:797] GIT: Running(<redacted>): git log -n1 --format=%H -- src/CustomerPortal/Message/Changes/Items/ReplaceItemsMessage.php
2022-11-17 15:15:09,803 [ 341545]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:803] GIT: Awaiting(<redacted>): git log -n1 --format=%H -- src/CustomerPortal/Message/Changes/Items/ReplaceItemsMessage.php
2022-11-17 15:15:09,804 [ 341546]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:803] GIT: Awaiting(<redacted>): git log -n1 --format=%H -- src/CustomerPortal/Message/Changes/Items/ReplaceItemsMessage.php
2022-11-17 15:15:09,804 [ 341546]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:804] GIT: Completed(undefined): git config --get user.email in 44 ms
2022-11-17 15:15:09,804 [ 341546]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:804] GIT: Running(undefined): git config --get user.name
2022-11-17 15:15:09,809 [ 341551]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:808] [2b6] GitHubProvider.getBoards
2022-11-17 15:15:09,809 [ 341551]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:809] [2b7] GitService.getRepoRemotes
2022-11-17 15:15:09,809 [ 341551]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:809] [2b7] GitService.getRepoRemotes returned [<redacted>] • 0 ms
2022-11-17 15:15:09,809 [ 341551]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:809] [2b6] GitHubProvider.getBoards completed • 0 ms
2022-11-17 15:15:09,810 [ 341552]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:810] [2b8] GitHubProvider.getCards
2022-11-17 15:15:09,814 [ 341556]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:814] [2b9] ScmManager.getRepos
2022-11-17 15:15:09,816 [ 341558]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:816] GIT: Running(<redacted>): git rev-parse --abbrev-ref HEAD
2022-11-17 15:15:09,822 [ 341564]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:822] GIT: Completed(undefined): git config --get user.name in 18 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] GIT: Completed(<redacted>): git log -n1 --format=%H -- src/CustomerPortal/Message/Changes/Items/ReplaceItemsMessage.php in 30 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] GIT: Completed(<redacted>): git log -n1 --format=%H -- src/CustomerPortal/Message/Changes/Items/ReplaceItemsMessage.php in 24 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] GIT: Completed(<redacted>): git log -n1 --format=%H -- src/CustomerPortal/Message/Changes/Items/ReplaceItemsMessage.php in 24 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2bb] GitService.getRepoRemotes
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2bc] GitService.getRepoRemotes
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2bd] GitService.getRepoRemotes
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2bb] GitService.getRepoRemotes returned [<redacted>] • 0 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2bc] GitService.getRepoRemotes returned [<redacted>] • 0 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2bd] GitService.getRepoRemotes returned [<redacted>] • 0 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2af] ScmManager.getFileInfo completed • 62 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2b0] ScmManager.getFileInfo completed • 48 ms
2022-11-17 15:15:09,828 [ 341570]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:828] [2b1] ScmManager.getFileInfo completed • 48 ms
2022-11-17 15:15:09,829 [ 341571]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:829] github getMyPullRequests {"prQueries":[{"providerId":"github*com","name":"Waiting on my Review","query":"is:pr is:open involves:@me","hidden":false},{"providerId":"github*com","name":"Assigned to Me","query":"is:pr is:open assignee:@me","hidden":false},{"providerId":"github*com","name":"Created by Me","query":"is:pr is:open author:@me","hidden":false},{"providerId":"github*com","name":"Recent","query":"recent","hidden":false}],"isOpen":false,"force":true}
2022-11-17 15:15:09,829 [ 341571]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:829] [2be] ThirdPartyProviderRegistry.getProviderDefaultPullRequestQueries
2022-11-17 15:15:09,829 [ 341571]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:829] [2be] ThirdPartyProviderRegistry.getProviderDefaultPullRequestQueries completed • 0 ms
2022-11-17 15:15:09,829 [ 341571]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:829] getMyPullRequests providerId="github*com" finalQuery="is:pr is:open involves:@me" login=veloxy
2022-11-17 15:15:09,829 [ 341571]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:829] getMyPullRequests providerId="github*com" finalQuery="is:pr is:open assignee:@me" login=veloxy
2022-11-17 15:15:09,829 [ 341571]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:829] getMyPullRequests providerId="github*com" finalQuery="is:pr is:open author:@me" login=veloxy
2022-11-17 15:15:09,829 [ 341571]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:829] getMyPullRequests providerId="github*com" finalQuery="is:pr author:@me" login=veloxy
2022-11-17 15:15:09,832 [ 341574]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:832] GIT: Completed(<redacted>): git rev-parse --abbrev-ref HEAD in 17 ms
2022-11-17 15:15:09,832 [ 341574]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:832] [2c0] GitService.getRepoRemotes
2022-11-17 15:15:09,832 [ 341574]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:832] [2c0] GitService.getRepoRemotes returned [<redacted>] • 0 ms
2022-11-17 15:15:09,832 [ 341574]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:832] [2b9] ScmManager.getRepos completed • 17 ms
2022-11-17 15:15:09,832 [ 341574]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:832] [2c1] ScmManager.getRepos
2022-11-17 15:15:09,832 [ 341574]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:832] GIT: Running(<redacted>): git rev-parse --abbrev-ref HEAD
2022-11-17 15:15:09,836 [ 341578]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:835] [2c2] CodeStreamApiProvider.updatePreferences
2022-11-17 15:15:09,838 [ 341580]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:838] [2c3] ScmManager.getRepos
2022-11-17 15:15:09,838 [ 341580]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:838] [2c3] ScmManager.getRepos completed • 0 ms
2022-11-17 15:15:09,839 [ 341581]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:839] [2c4] ScmManager.getRepos
2022-11-17 15:15:09,839 [ 341581]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:839] [2c4] ScmManager.getRepos completed • 0 ms
2022-11-17 15:15:09,839 [ 341581]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:839] [2c5] ScmManager.getRepos
2022-11-17 15:15:09,839 [ 341581]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:839] [2c5] ScmManager.getRepos completed • 0 ms
2022-11-17 15:15:09,840 [ 341582]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:840] GIT: Completed(<redacted>): git rev-parse --abbrev-ref HEAD in 8 ms
2022-11-17 15:15:09,841 [ 341583]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:840] [2c1] ScmManager.getRepos completed • 8 ms
2022-11-17 15:15:09,844 [ 341586]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:844] MARKERS: requested document markers for /<redacted>/Message/Changes/Items/ReplaceItemsMessage.php
2022-11-17 15:15:09,844 [ 341586]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:844] MARKERS: found cached codemark document markers for /<redacted>/Message/Changes/Items/ReplaceItemsMessage.php v1
2022-11-17 15:15:09,918 [ 341660]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:918] API server status: 200
2022-11-17 15:15:09,920 [ 341662]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:919] registerApiCapabilities for teamId 636cfde05d6ec58a8d71b6e2 — {}
2022-11-17 15:15:09,920 [ 341662]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:920] _apiCapabilities — {"sample":{"description":"SAMPLE","version":"1.0.0"},"multipleMarkers":{"description":"Ability to have multiple code blocks per codemark","version":"1.21.20"},"moveMarkers":{"description":"Ability to change the location of code blocks pointed to by codemarks","version":"1.21.20"},"moveMarkers2":{"description":"Ability to change the location of code blocks pointed to by codemarks, with essential API server fix","version":"1.21.23"},"repoCommitMatching":{"description":"Supports the /repos/match/:teamId call, which allows matches to be found for repos by remotes and known commit hashes","version":"1.21.24"},"follow":{"description":"Ability to follow or unfollow a codemark","version":"1.21.27"},"lightningCodeReviews":{"description":"Support for lightning code reviews","version":"1.21.33","supportedIdes":["VS Code","JetBrains","VS"]},"notificationDeliveryPreference":{"description":"Support for displaying the email/desktop delivery notification preference","version":"1.21.33"},"multipleReviewersApprove":{"description":"Support for multiple reviewers being required to approve a review","version":"7.1.1"},"emailSupport":{"description":"Whether outbound emails are supported, value actually comes from configuration","version":"1.0.0"},"multiCheckpointReviews":{"description":"Reviews supporting multiple checkpoints","version":"7.2.0"},"inviteUsersOnTheFly":{"description":"Users can be invited on-the-fly in codemarks and reviews","version":"7.2.7"},"kickstart":{"description":"Kickstart features","version":"7.4.2"},"cr2pr":{"description":"Features supporting opening pull requests after code reviews","version":"7.4.2"},"shareStatusToSlack":{"description":"Whether the share to slack capability is supported, which requires a new scope for the slack app","version":"8.0.6"},"addBlameMap":{"description":"Supporting adding someone to the blame-map","version":"8.1.1"},"vsCodeGithubSignin":{"description":"Supports whether special VSCode GitHub signin is supported in the auth flow","version":"8.2.7"},"compactModifiedRepos":{"description":"Supports compact modifiedRepos structure","version":"8.2.8"},"providerReauth":{"description":"Supports re-authentication for providers if tokens are found to be invalid","version":"8.2.11"},"autoJoin":{"description":"Supports auto-join API call, to auto-join a team based on open repos in IDE","version":"8.2.13"},"testGroups":{"description":"Supports the /company-test-groups/:id call, to set randomized test groups for a company","version":"8.2.15"},"fileUploads":{"description":"Supports file uploading","version":"8.2.17","cloudOnly":true},"autoFR":{"description":"Supports automatic generation of feedback requests","version":"8.2.20"},"readItem":{"description":"Supports /read-item call to mark number of unread replies for an item","version":"8.2.33"},"echoes":{"description":"Supports periodic echoes to test broadcaster reliability","version":"8.2.39"},"multiRegion":{"description":"Supports multi-region switching","version":"12.0.7","useGlobal":true}}
2022-11-17 15:15:09,920 [ 341662]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:920] Got environment from connectivity response: — {"environment":"eu","isOnPrem":false,"isProductionCloud":true,"newRelicLandingServiceUrl":"https://landing.service.newrelic.com","newRelicApiUrl":"https://api.eu.newrelic.com","environmentHosts":[{"name":"EU","publicApiUrl":"https://eu-api.codestream.com","shortName":"eu"},{"name":"US","publicApiUrl":"https://api.codestream.com","shortName":"us"}]}
2022-11-17 15:15:09,920 [ 341662]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:920] [2c8] CodeStreamAgent.sendNotification(codestream/didSetEnvironment)
2022-11-17 15:15:09,920 [ 341662]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:920] [2c8] CodeStreamAgent.sendNotification(codestream/didSetEnvironment) completed • 0 ms
2022-11-17 15:15:09,920 [ 341662]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:09:920] [2ae] CodeStreamSession.verifyConnectivity completed • 202 ms
2022-11-17 15:15:10,072 [ 341814]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:072] API(9523b136-68a6-4e33-b678-f06a283e900f): Completed PUT /preferences body={"skipGitEmailCheck":true} • 236 ms
2022-11-17 15:15:10,072 [ 341814]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:072] [2cb] CodeStreamAgent.sendNotification(codestream/didChangeData:users)
2022-11-17 15:15:10,074 [ 341816]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:074] [2cb] CodeStreamAgent.sendNotification(codestream/didChangeData:users) completed • 1 ms
2022-11-17 15:15:10,074 [ 341816]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:074] [2cc] CodeStreamAgent.sendNotification(codestream/didChangeData:preferences)
2022-11-17 15:15:10,074 [ 341816]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:074] [2cc] CodeStreamAgent.sendNotification(codestream/didChangeData:preferences) completed • 0 ms
2022-11-17 15:15:10,074 [ 341816]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:074] [2c2] CodeStreamApiProvider.updatePreferences completed • 238 ms
2022-11-17 15:15:10,076 [ 341818]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:076] MARKERS: requested document markers for /<redacted>/Message/Changes/Items/ReplaceItemsMessage.php
2022-11-17 15:15:10,076 [ 341818]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:076] MARKERS: calculating codemark document markers for /<redacted>/Message/Changes/Items/ReplaceItemsMessage.php v1
2022-11-17 15:15:10,108 [ 341850]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:108] BROADCASTER: PUBNUB: Message received on user-636cfddd64564609f6886b03 at 1668694510592
2022-11-17 15:15:10,108 [ 341850]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:108] BROADCASTER: Broadcaster message received at: 1668694510592
2022-11-17 15:15:10,108 [ 341850]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:108] BROADCASTER: _lastMessageReceivedAt updated to 1668694510592
2022-11-17 15:15:10,418 [ 342160]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:418] GitHub: Completed GET /search/issues?q=archived%3Afalse%20is%3Aissue%20is%3Aopen%20assignee%3A%40me&sort=updated • 607 ms
2022-11-17 15:15:10,418 [ 342160]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:418] search limit used 29 of 30, reset at Thu Nov 17 2022 15:16:10 GMT+0100 (Central European Standard Time)
2022-11-17 15:15:10,418 [ 342160]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:418] [2b8] GitHubProvider.getCards completed • 608 ms
2022-11-17 15:15:10,678 [ 342420]   INFO - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:678] Webview error: Cannot read properties of undefined (reading 'login')
TypeError: Cannot read properties of undefined (reading 'login')
    at cantCheckoutReason (../../../../../shared/ui/Stream/OpenPullRequests.tsx:856:40)
    at renderPrGroup (../../../../../shared/ui/Stream/OpenPullRequests.tsx:1010:24)
    at (../../../../../shared/ui/Stream/OpenPullRequests.tsx:1579:16)
    at Array.map (<anonymous>)
    at (../../../../../shared/ui/Stream/OpenPullRequests.tsx:1578:16)
    at Array.map (<anonymous>)
    at renderQueryGroup (../../../../../shared/ui/Stream/OpenPullRequests.tsx:1534:36)
    at (../../../../../shared/ui/Stream/OpenPullRequests.tsx:1704:46)
    at Array.map (<anonymous>)
    at (../../../../../shared/ui/Stream/OpenPullRequests.tsx:1704:30)
2022-11-17 15:15:10,679 [ 342421]   WARN - #c.c.a.CodeStreamLanguageClient - [2022-11-17 14:15:10:679] Ignoring duplicate error — {"key":"RH29/xXBQCQBeommllSl3g=="}
```

Note: I replaced some file paths and repo urls with `<redacted`

**Comment by marcelofarias** [comment]
Hi @veloxy! This issue was fixed in 14.7.0+277. Would you mind upgrading to the latest version of CodeStream and trying again?

**Comment by marcelofarias** [comment]
Actually this is a slightly different issue - it will be fixed in the next release. Thanks for the report!

**Comment by planteater** [comment]
@veloxy - We have a fix that will go out on Monday, but if you want to try it out now the link below has a pre-release version of the extension.

https://drive.google.com/file/d/1e_XCExMBinNY24wA4Rkx9BZ2n1OvC6_a/view?usp=share_link

You can install by going to Preferences/Settings > Plugins and then select “Install plugin from disk” from the gear menu at the top-right. Then restart your IDE. Let us know how it goes.

**Comment by veloxy** [comment]
> @veloxy - We have a fix that will go out on Monday, but if you want to try it out now the link below has a pre-release version of the extension.
> 
> https://drive.google.com/file/d/1e_XCExMBinNY24wA4Rkx9BZ2n1OvC6_a/view?usp=share_link
> 
> You can install by going to Preferences/Settings > Plugins and then select “Install plugin from disk” from the gear menu at the top-right. Then restart your IDE. Let us know how it goes.

@planteater @marcelofarias that fixed it, thanks!
