### ISSUE TITLE
Failure to Fetch Respositories

### ISSUE THREAD

**Issue by amacgregor** [TeamCodeStream/CodeStream#130]
**Describe the bug**
Experiencing an error trying to retrieve the repository list from github on VS code, everything is connected however there seems to be some sort of failure. Logs attached 

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [5.2.0]
 - OS + version: [MacOS 10.14]
 - IDE + version: [VS Code 1.40.1]

**Log Files**
Attached log files:

```
[2019-11-18 11:34:57:911] [1ae] SlackApiProvider.getUser
[2019-11-18 11:34:57:911] [1af] CodeStreamApiProvider.getUser
[2019-11-18 11:34:57:911] [1b0] CodeStreamApiProvider.getMe
[2019-11-18 11:34:58:073] [1b1] VersionMiddlewareManager.setApiVersion
[2019-11-18 11:34:58:073] [1b1] VersionMiddlewareManager.setApiVersion completed • 0 ms
[2019-11-18 11:34:58:073] API(5b218fc3-c495-4753-8e21-e1fa65f877d5): Completed GET /users/me • 162 ms
[2019-11-18 11:34:58:073] [1b0] CodeStreamApiProvider.getMe completed • 162 ms
[2019-11-18 11:34:58:073] [1af] CodeStreamApiProvider.getUser completed • 162 ms
[2019-11-18 11:34:58:073] [1ae] SlackApiProvider.getUser completed • 162 ms
[2019-11-18 11:34:58:074] [1b2] SlackApiProvider.getMe
[2019-11-18 11:34:58:074] [1b3] CodeStreamApiProvider.getMe
[2019-11-18 11:34:58:227] [1b4] VersionMiddlewareManager.setApiVersion
[2019-11-18 11:34:58:227] [1b4] VersionMiddlewareManager.setApiVersion completed • 0 ms
[2019-11-18 11:34:58:228] API(f967a655-2b60-4cb7-b609-ad984358c02a): Completed GET /users/me • 154 ms
[2019-11-18 11:34:58:228] [1b3] CodeStreamApiProvider.getMe completed • 154 ms
[2019-11-18 11:34:58:369] [1b2] SlackApiProvider.getMe completed • 295 ms
[2019-11-18 11:34:58:369] [1b9] SlackApiProvider.onCodeStreamMessage(users)
[2019-11-18 11:34:58:369] [1ba] SlackApiProvider.getMe
[2019-11-18 11:34:58:369] [1bb] CodeStreamApiProvider.getMe
[2019-11-18 11:34:58:541] [1bc] VersionMiddlewareManager.setApiVersion
[2019-11-18 11:34:58:541] [1bc] VersionMiddlewareManager.setApiVersion completed • 0 ms
[2019-11-18 11:34:58:541] API(2a10f867-7d1b-4afd-8489-05b50190eee4): Completed GET /users/me • 172 ms
[2019-11-18 11:34:58:541] [1bb] CodeStreamApiProvider.getMe completed • 172 ms
[2019-11-18 11:34:58:683] [1ba] SlackApiProvider.getMe completed • 313 ms
[2019-11-18 11:34:58:683] [1c1] CodeStreamAgent.sendNotification(codestream/didChangeData:users)
[2019-11-18 11:34:58:683] [1c1] CodeStreamAgent.sendNotification(codestream/didChangeData:users) completed • 0 ms
[2019-11-18 11:34:58:683] [1b9] SlackApiProvider.onCodeStreamMessage(users) completed • 314 ms
[2019-11-18 11:34:58:889] GitHub: Completed GET /user • 205 ms
[2019-11-18 11:34:58:920] [1c3] GitHubProvider.getBoards
[Error - 6:34:58 AM] [2019-11-18 11:34:58:921] [1c3] GitHubProvider.getBoards — failed • 0 ms
Error: Internal Server Error
Error: Internal Server Error
    at CodeStreamApiProvider.handleErrorResponse (/Users/amacgregor/.vscode/extensions/codestream.codestream-5.2.0/dist/agent.js:27:300340)
    at CodeStreamApiProvider.fetch (/Users/amacgregor/.vscode/extensions/codestream.codestream-5.2.0/dist/agent.js:27:299341```

**Comment by marcelofarias** [comment]
Hi @amacgregor! Thanks for the report. The issue should now be fixed.
