### ISSUE TITLE
Error  on WebStorm IDE

### ISSUE THREAD

**Issue by krxdow** [TeamCodeStream/codestream#1420]
Hi everyone 
I have an error with the plugin on WebStorm IDE,
I try to uninstall and restart, it gives me the same problem

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@30cd565b, Dispatchers.Default]

java.lang.Error: factory already defined
	at java.base/java.net.URL.setURLStreamHandlerFactory(URL.java:1228)
	at com.codestream.system.CodeStreamDiffURLStreamHandler.initUrlHandler(CodeStreamDiffURLStreamHandler.kt:17)
	at com.codestream.system.CodeStreamDiffURLStreamHandler.<clinit>(CodeStreamDiffURLStreamHandler.kt:11)
	at com.codestream.CodeStreamProjectService.<init>(CodeStreamProjectService.kt:53)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:91)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:714)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at com.codestream.DirectoryKt.getServiceIfNotDisposed(Directory.kt:56)
	at com.codestream.DirectoryKt.getCodeStream(Directory.kt:17)
	at com.codestream.agent.AgentService.initAgent(AgentService.kt:168)
	at com.codestream.agent.AgentService.initAgent$default(AgentService.kt:164)
	at com.codestream.agent.AgentService$1.invokeSuspend(AgentService.kt:153)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@30cd565b, Dispatchers.Default]
```

**Comment by bcanzanella** [comment]
Hi @krxdow sorry you're running into this. 

Could you send a copy of your CodeStream logs and a list of any other extensions you have installed to us at codestream@newrelic.com ? We suspect there is a problem with the coroutine scope running in a classloader where another plugin registered a url scheme.

Instructions for finding your CodeStream logs can be found here: https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/

thanks

**Comment by krxdow** [comment]
I tried to find the conflicting plugin

and do something like

```
for (URLStreamHandlerFactory factory: URL.getURLStreamHandlerFactory().factories()) {
    System.out.println(factory);
}
```

[webstorm-logs-20230407-0035406067169977273715835.zip](https://github.com/TeamCodeStream/codestream/files/11174824/webstorm-logs-20230407-0035406067169977273715835.zip)

**Comment by krxdow** [comment]
According to my empirical tests, it seems that there is a conflict with the codetogether plugin, which allows me to collaborate live

**Comment by planteater** [comment]
@krxdow this should be fixed in CodeStream 14.19.
