### ISSUE TITLE
Jetbrains plugins crash: Property must not be null: uri

### ISSUE THREAD

**Issue by Karsei** [TeamCodeStream/codestream#1459]
- CodeStream Extension version: 14.18.1+307
- IDE Version: Intellij IDEA 2022.3.2 (Ultimate Edition)
- OS Version: Windows 10 Pro 22H2 19045.2913

I first installed the codestream plugin from the IDE's Marketplace.

After that, if I restart the IDE or just start it, it always crashes with the error log as below.

```
java.lang.NullPointerException: Property must not be null: uri
	at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
	at org.eclipse.lsp4j.WorkspaceFolder.<init>(WorkspaceFolder.java:42)
	at com.codestream.extensions.ProjectKt.getBaseWorkspaceFolder(Project.kt:29)
	at com.codestream.extensions.ProjectKt.getWorkspaceFolders(Project.kt:16)
	at com.codestream.agent.AgentService.initializationOptions(AgentService.kt:490)
	at com.codestream.agent.AgentService.getInitializeParams(AgentService.kt:457)
	at com.codestream.agent.AgentService.initAgent(AgentService.kt:186)
	at com.codestream.agent.AgentService.initAgent$default(AgentService.kt:166)
	at com.codestream.agent.AgentService$1.invokeSuspend(AgentService.kt:155)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

However, I've confirmed that it works well in other projects.

So, as a result of comparing and analyzing, it was confirmed that it does not work if there are special characters in the address.

for example,

```
W:\programming\git\demo (works)
W:\[programming]\[git]\demo (doesn't work)
```

If there are special characters in the project address, it doesn't seem to work properly.

**Comment by planteater** [comment]
My apologies for letting this one slip through the cracks @Karsei. I'll have someone check into this asap.

**Comment by planteater** [comment]
Fixed in latest version,
