### ISSUE TITLE
Constant and repeating lags in IntelliJ Idea code editor

### ISSUE THREAD

**Issue by Ziggizag** [TeamCodeStream/codestream#1519]
2023-06-13 14:11:54,624 [2145993]   WARN - #com.codestream.agent.AgentService - }
2023-06-13 14:11:54,625 [2145994]   WARN - #com.codestream.agent.AgentService - Ignoring duplicate error {
2023-06-13 14:11:54,625 [2145994]   WARN - #com.codestream.agent.CodeStreamLanguageClient - [2023-06-13 12:11:54:625] getSpans none — {"locator":{"namespaces":["console\\controllers\\OdbcReportController","console\\controllers"]},"resolutionMethod":"hybrid","relativeFilePath":"\\console\\controllers\\OdbcReportController.php","accountId":1819429}
2023-06-13 14:11:54,625 [2145994]   WARN - #com.codestream.agent.AgentService -   key: 'XXXXXXXX',
2023-06-13 14:11:54,626 [2145995]   WARN - #com.codestream.agent.AgentService -   message: 'NRQL Syntax Error: Error at line 1 position 150, perhaps unterminated \': {"response":{"data":{"actor":{"account":{"nrql":null}}},"errors":[{"extensions":{"errorClass":"INVALID_INPUT"},"locations":[{"column":6,"line":4}],"message":"NRQL Syntax Error: Error at line 1 position 150, perhaps unterminated \'","path":["actor","account","nrql"]}],"status":200,"headers":{}},"request":{"query":"query Nrql($accountId:Int!) {\\n\\t\\t\\tactor {\\n\\t\\t\\t\\taccount(id: $accountId) {\\n\\t\\t\\t\\t\\tnrql(query: \\"FROM Span SELECT latest(code.filepath) as codeFilePath WHERE `entity.guid` = \'MTgxOTQyOXxBUE18QVBQTElDQVRJT058MTk1MzM1MTc4\' AND `code.filepath` LIKE \'%\\\\console\\\\controllers\\\\OdbcReportController.php\' FACET name SINCE 30 minutes AGO LIMIT 100\\", timeout: 60) {\\n\\t\\t\\t\\t\\t\\tresults\\n\\t\\t\\t\\t\\t}\\n\\t\\t\\t\\t}\\n\\t\\t\\t}\\n\\t  \\t}","variables":{"accountId":1819429}}}'
2023-06-13 14:11:54,626 [2145995]   INFO - #com.codestream.agent.CodeStreamLanguageClient - [2023-06-13 12:11:54:626] getFileLevelTelemetry no spans — {"hasAnyData":0,"relativeFilePath":"\\console\\controllers\\OdbcReportController.php","newRelicEntityGuid":"MTgxOTQyOXxBUE18QVBQTElDQVRJT058MTk1MzM1MTc4","newRelicAccountId":1819429}
2023-06-13 14:11:54,627 [2145996]   INFO - #com.codestream.agent.CodeStreamLanguageClient - [2023-06-13 12:11:54:626] [432] NewRelicProvider.getFileLevelTelemetry completed • 10418 ms
2023-06-13 14:11:54,627 [2145996]   WARN - #com.codestream.agent.AgentService - }
2023-06-13 14:11:54,663 [2146032]   WARN - #com.codestream.agent.CodeStreamLanguageClient - [2023-06-13 12:11:54:662] NR: query caught: — {"zetails":{"nrUrl":"https://api.newrelic.com/graphql","versionInfo":{"version":"14.22.1","build":"314"},"ide":{"name":"JetBrains","version":"2023.1.2","detail":"IntelliJ IDEA Ultimate Edition"},"isProductionCloud":true}}
Error: NRQL Syntax Error: Error at line 1 position 150, perhaps unterminated ': {"response":{"data":{"actor":{"account":{"nrql":null}}},"errors":[{"extensions":{"errorClass":"INVALID_INPUT"},"locations":[{"column":6,"line":4}],"message":"NRQL Syntax Error: Error at line 1 position 150, perhaps unterminated '","path":["actor","account","nrql"]}],"status":200,"headers":{}},"request":{"query":"query Nrql($accountId:Int!) {\n\t\t\tactor {\n\t\t\t\taccount(id: $accountId) {\n\t\t\t\t\tnrql(query: \"FROM Span SELECT latest(code.filepath) as codeFilePath WHERE `entity.guid` = 'MTgxOTQyOXxBUE18QVBQTElDQVRJT058MTk1MzM1MTc4' AND `code.filepath` LIKE '%\\console\\controllers\\OdbcReportController.php' FACET name SINCE 30 minutes AGO LIMIT 100\", timeout: 60) {\n\t\t\t\t\t\tresults\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t  \t}","variables":{"accountId":1819429}}}
Error: NRQL Syntax Error: Error at line 1 position 150, perhaps unterminated ': {"response":{"data":{"actor":{"account":{"nrql":null}}},"errors":[{"extensions":{"errorClass":"INVALID_INPUT"},"locations":[{"column":6,"line":4}],"message":"NRQL Syntax Error: Error at line 1 position 150, perhaps unterminated '","path":["actor","account","nrql"]}],"status":200,"headers":{}},"request":{"query":"query Nrql($accountId:Int!) {\n\t\t\tactor {\n\t\t\t\taccount(id: $accountId) {\n\t\t\t\t\tnrql(query: \"FROM Span SELECT latest(code.filepath) as codeFilePath WHERE `entity.guid` = 'MTgxOTQyOXxBUE18QVBQTElDQVRJT058MTk1MzM1MTc4' AND `code.filepath` LIKE '%\\console\\controllers\\OdbcReportController.php' FACET name SINCE 30 minutes AGO LIMIT 100\", timeout: 60) {\n\t\t\t\t\t\tresults\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t  \t}","variables":{"accountId":1819429}}}
    at ClientError (C:\Users\szczesnz\.codestream\node_modules\graphql-request\src\index.ts:394:11)
    at ClientError (C:\Users\szczesnz\.codestream\node_modules\graphql-request\src\types.ts:26:14)
    at Object.ClientError [as next] (C:\Users\szczesnz\.codestream\node_modules\graphql-request\src\types.ts:26:14)
    at fulfilled (C:\Users\szczesnz\.codestream\node_modules\graphql-request\src\types.ts:26:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by planteater** [comment]
Thanks for reaching out @Ziggizag. Any chance I could trouble you for a screen recording showing the lag, as well as a complete log file? To grab the log file, go to Help > Collect Logs and Diagnostic Data in your IDE. This will open the finder where you should see a newly created zip file.

Feel free to send both to me at codestream@newrelic.com if you'd prefer not to post them here. Thanks!

**Comment by planteater** [comment]
@Ziggizag - Just wanted to follow up on my earlier reply. Thanks!

**Comment by planteater** [comment]
@Ziggizag I'm going to close this out for now, but when you get the chance send that info to me at codestream@newrelic.com and we'll dig right in. Thanks
