### ISSUE TITLE
Codestream plugin in CLion is unusable

### ISSUE THREAD

**Issue by andrey-chu** [TeamCodeStream/CodeStream#166]
Since recently I am unable to use codestream in CLion.
When trying to add the comment to any file that was not previously commented on in codestream. I receive : There was an error creating the codemark. the error in log file (attached) is: `2020-03-30 14:47:35,766 [ 182168]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:35:766] Searching for repositories (depth=2) in '/home/andrey/CLionProjects/ALMaSS_all/HoneyBee' took 9 ms 
2020-03-30 14:47:35,766 [ 182168]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:35:766] repositorySearch found 1 repos 
2020-03-30 14:47:35,766 [ 182168]   WARN - destream.webview.WebViewRouter - Request codestream/codemarks/sharing/create failed with message: Could not retrieve contents for /home/andrey/CLionProjects/ALMaSS_all/HoneyBee/hbspreadsheet.cpp@bf03539562475e367e71f9eb086de462c3319f33 
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request codestream/codemarks/sharing/create failed with message: Could not retrieve contents for /home/andrey/CLionProjects/ALMaSS_all/HoneyBee/hbspreadsheet.cpp@bf03539562475e367e71f9eb086de462c3319f33
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-30 14:47:35,767 [ 182169]  DEBUG - destream.webview.WebViewRouter - Posting response wv:91:41Rg91-nQ3eSJX3Mrt8m_g - Error: Request codestream/codemarks/sharing/create failed with message: Could not retrieve contents for /home/andrey/CLionProjects/ALMaSS_all/HoneyBee/hbspreadsheet.cpp@bf03539562475e367e71f9eb086de462c3319f33 
2020-03-30 14:47:35,778 [ 182180]  DEBUG - destream.webview.WebViewRouter - Handling codestream/reporting/message wv:92:QHGeLm4oTqaaU4HxCNoLWg`

At the same time the same thing works if there was previously a comment in the same file:
`2020-03-30 14:47:10,658 [ 157060]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:10:658] [31d] CodeStreamApiProvider.createPost — {"codemark":{"codeBlocks":[{"uri":"file:///data/au517882/CLionProjects/ALMaSS_all/GooseManagement/Goose_Base.cpp","range":{"cursor":{"line":97,"character":36},"start":{"line":87,"character":7},"end":{"line":97,"character":36}},"contents":"Goose_Base::m_flightcost = -1;\ndouble Goose_Base::m_mingooseforagerate[ 3 ] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseMaxAppetiteScaler = -1;\ndouble Goose_Base::m_GooseMaxEnergyReserveProportion = -1;\ndouble Goose_Base::m_GooseKJtoFatConversion = -1;\ndouble Goose_Base::m_GooseFattoKJConversion = -1;\ndouble Goose_Base::m_GooseMinForageOpenness = -1;\ndouble Goose_Base::m_GooseLeavingThreshold = -1;\ndouble Goose_Base::m_GooseForageDistX2[3] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseForageDist[3] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseFieldForag","scm":{"file":"GooseManagement/Goose_Base.cpp","repoPath":"/data/au517882/CLionProjects/ALMaSS_all","repoId":"5e5e6f75dbc3a6605407ff90","revision":"c24d175acb5ab0604ecdd711946d2d5155353654","authors":[],"remotes":[{"name":"origin","url":"gitlab.com/christopping/almass_all"}],"branch":"InternalMaster"}}],"text":"test1","type":"comment","assignees":[],"title":"","tags":[],"relatedCodemarkIds":[],"isChangeRequest":false,"textDocuments":[{"uri":"file:///data/au517882/CLionProjects/ALMaSS_all/GooseManagement/Goose_Base.cpp"}],"entryPoint":"Context Menu","remotes":["gitlab.com/christopping/almass_all"],"mentionedUserIds":[],"markers":[{"code":"Goose_Base::m_flightcost = -1;\ndouble Goose_Base::m_mingooseforagerate[ 3 ] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseMaxAppetiteScaler = -1;\ndouble Goose_Base::m_GooseMaxEnergyReserveProportion = -1;\ndouble Goose_Base::m_GooseKJtoFatConversion = -1;\ndouble Goose_Base::m_GooseFattoKJConversion = -1;\ndouble Goose_Base::m_GooseMinForageOpenness = -1;\ndouble Goose_Base::m_GooseLeavingThreshold = -1;\ndouble Goose_Base::m_GooseForageDistX2[3] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseForageDist[3] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseFieldForag","commitHash":"c24d175acb5ab0604ecdd711946d2d5155353654","referenceLocations":[{"commitHash":"c24d175acb5ab0604ecdd711946d2d5155353654","location":[88,8,98,37,{}],"flags":{"canonical":true,"backtracked":false}},{"commitHash":"f1f38ecaf3e4ed9c10e541fa23b7feccffb7383f","location":[78,8,88,37,{"contentChanged":true}],"flags":{"backtracked":true}},{"commitHash":"d68d2e4ef12db68782446c4609b1696945753cdf","location":[75,8,85,37,{"contentChanged":true}],"flags":{"backtracked":true}},{"commitHash":"e32a97427a6c977b0405962142b6bd00d5c4e702","location":[69,8,82,37,{"contentChanged":true}],"flags":{"backtracked":true}}],"branchWhenCreated":"InternalMaster","remotes":["gitlab.com/christopping/almass_all"],"remoteCodeUrl":{"displayName":"GitLab","name":"gitlab","url":"https://gitlab.com/christopping/almass_all/blob/c24d175acb5ab0604ecdd711946d2d5155353654/GooseManagement/Goose_Base.cpp#L88-98"},"fileStreamId":"5e5e70101a225235b366a224"}],"remoteCodeUrl":{"displayName":"GitLab","name":"gitlab","url":"https://gitlab.com/christopping/almass_all/blob/c24d175acb5ab0604ecdd711946d2d5155353654/GooseManagement/Goose_Base.cpp#L88-98"}},"text":"test1","streamId":"5e5e6f74dbc3a6605407ff8f","dontSendEmail":false,"mentionedUserIds":[]} 
2020-03-30 14:47:11,063 [ 157465]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:11:063] [31e] VersionMiddlewareManager.setApiVersion — 6.4.0 
2020-03-30 14:47:11,063 [ 157465]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:11:063] [31e] VersionMiddlewareManager.setApiVersion completed • 0 ms 
2020-03-30 14:47:11,064 [ 157466]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:11:063] API(ced0668e-d3ca-4652-bf20-6a86ec7f7866): Completed POST /posts body={"codemark":{"codeBlocks":[{"uri":"file:///data/au517882/CLionProjects/ALMaSS_all/GooseManagement/Goose_Base.cpp","range":{"cursor":{"line":97,"character":36},"start":{"line":87,"character":7},"end":{"line":97,"character":36}},"contents":"Goose_Base::m_flightcost = -1;\ndouble Goose_Base::m_mingooseforagerate[ 3 ] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseMaxAppetiteScaler = -1;\ndouble Goose_Base::m_GooseMaxEnergyReserveProportion = -1;\ndouble Goose_Base::m_GooseKJtoFatConversion = -1;\ndouble Goose_Base::m_GooseFattoKJConversion = -1;\ndouble Goose_Base::m_GooseMinForageOpenness = -1;\ndouble Goose_Base::m_GooseLeavingThreshold = -1;\ndouble Goose_Base::m_GooseForageDistX2[3] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseForageDist[3] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseFieldForag","scm":{"file":"GooseManagement/Goose_Base.cpp","repoPath":"/data/au517882/CLionProjects/ALMaSS_all","repoId":"5e5e6f75dbc3a6605407ff90","revision":"c24d175acb5ab0604ecdd711946d2d5155353654","authors":[],"remotes":[{"name":"origin","url":"gitlab.com/christopping/almass_all"}],"branch":"InternalMaster"}}],"text":"test1","type":"comment","assignees":[],"title":"","tags":[],"relatedCodemarkIds":[],"isChangeRequest":false,"textDocuments":[{"uri":"file:///data/au517882/CLionProjects/ALMaSS_all/GooseManagement/Goose_Base.cpp"}],"entryPoint":"Context Menu","remotes":["gitlab.com/christopping/almass_all"],"mentionedUserIds":[],"markers":[{"code":"Goose_Base::m_flightcost = -1;\ndouble Goose_Base::m_mingooseforagerate[ 3 ] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseMaxAppetiteScaler = -1;\ndouble Goose_Base::m_GooseMaxEnergyReserveProportion = -1;\ndouble Goose_Base::m_GooseKJtoFatConversion = -1;\ndouble Goose_Base::m_GooseFattoKJConversion = -1;\ndouble Goose_Base::m_GooseMinForageOpenness = -1;\ndouble Goose_Base::m_GooseLeavingThreshold = -1;\ndouble Goose_Base::m_GooseForageDistX2[3] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseForageDist[3] = { -1, -1, -1 };\ndouble Goose_Base::m_GooseFieldForag","commitHash":"c24d175acb5ab0604ecdd711946d2d5155353654","referenceLocations":[{"commitHash":"c24d175acb5ab0604ecdd711946d2d5155353654","location":[88,8,98,37,{}],"flags":{"canonical":true,"backtracked":false}},{"commitHash":"f1f38ecaf3e4ed9c10e541fa23b7feccffb7383f","location":[78,8,88,37,{"contentChanged":true}],"flags":{"backtracked":true}},{"commitHash":"d68d2e4ef12db68782446c4609b1696945753cdf","location":[75,8,85,37,{"contentChanged":true}],"flags":{"backtracked":true}},{"commitHash":"e32a97427a6c977b0405962142b6bd00d5c4e702","location":[69,8,82,37,{"contentChanged":true}],"flags":{"backtracked":true}}],"branchWhenCreated":"InternalMaster","remotes":["gitlab.com/christopping/almass_all"],"remoteCodeUrl":{"displayName":"GitLab","name":"gitlab","url":"https://gitlab.com/christopping/almass_all/blob/c24d175acb5ab0604ecdd711946d2d5155353654/GooseManagement/Goose_Base.cpp#L88-98"},"fileStreamId":"5e5e70101a225235b366a224"}],"remoteCodeUrl":{"displayName":"GitLab","name":"gitlab","url":"https://gitlab.com/christopping/almass_all/blob/c24d175acb5ab0604ecdd711946d2d5155353654/GooseManagement/Goose_Base.cpp#L88-98"}},"text":"test1","streamId":"5e5e6f74dbc3a6605407ff8f","dontSendEmail":false,"mentionedUserIds":[],"teamId":"5e5e6f74dbc3a6605407ff8d"} • 405 ms 
2020-03-30 14:47:11,064 [ 157466]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:11:064] [31d] CodeStreamApiProvider.createPost completed • 405 ms 
2020-03-30 14:47:11,064 [ 157466]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:11:064] createSharingCodemarkPost: will save uncommitted locations 
2020-03-30 14:47:11,064 [ 157466]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:11:064] [31f] CodemarksManager.resolve — {"type":"codemarks","data":[{"version":1,"deactivated":false,"streamId":"5e5e6f74dbc3a6605407ff8f","postId":"5e81ea4e7b452523b91c242a","numReplies":0,"pinned":true,"createdAt":1585572430994,"modifiedAt":1585572430995,"text":"test1","type":"comment","title":"","tags":[],"relatedCodemarkIds":[],"remoteCodeUrl":{"name":"gitlab","url":"https://gitlab.com/christopping/almass_all/blob/c24d175acb5ab0604ecdd711946d2d5155353654/GooseManagement/Goose_Base.cpp#L88-98"},"teamId":"5e5e6f74dbc3a6605407ff8d","origin":"JetBrains","creatorId":"5e5e6f56ab21d135b1ac4da8","markerIds":["5e81ea4e7b452523b91c242c"],"fileStreamIds":["5e5e70101a225235b366a224"],"followerIds":["5e5e6f56ab21d135b1ac4da8"],"permalink":"https://api.codestream.com/c/Xl5vdNvDpmBUB_-N/UiZz7xRJTJOvjVEbynkaYQ","lastActivityAt":1585572430994,"_id":"5e81ea4e7b452523b91c242b","id":"5e81ea4e7b452523b91c242b"}]} 
2020-03-30 14:47:11,064 [ 157466]   INFO - agent.CodeStreamLanguageClient - [2020-03-30 12:47:11:064] [800] CodemarkEntityCache.get completed(cache miss) • 0 ms — [["id","5e81ea4e7b452523b91c242b"]], {"fromCacheOnly":true} `

Tried: signing out/signing in. Using a beta version of the IDE (2020.1),  removing configuration from .CLion and configuring back again, removing .idea from the project  directory. Nothing helps.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 6.4.0+40
 - OS + version: ubuntu 18.04
 - IDE + version:CLion 2019.3.5
**Log Files**
[clion-logs-20200330-144752.zip](https://github.com/TeamCodeStream/CodeStream/files/4402967/clion-logs-20200330-144752.zip)

**Comment by planteater** [comment]
@andrey-chu - This should be resolved in v7.0 of our extension. Let us know how it goes!

**Comment by andrey-chu** [comment]
that solved this issue, thank you.
