### ISSUE TITLE
Cannot authenticate with GitLab

### ISSUE THREAD

**Issue by agnieszkajanicka** [TeamCodeStream/codestream#1764]
- CodeStream Extension version: 14.29.0+512
- IDE Version: Android Studio Giraffe | 2022.3.1 Patch 1, Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
- OS Version: MacOS Ventura 13.5.1 (22G90)

Steps to Reproduce:

1. Install plugin
2. Select authentication via GitLab
3. Allow integration via GitLab
4. Got Authentication Error from Code Stream web page after redirect
5. Get back to IDE plugin, see only "observability" section, nothing else

Same issue occurs when trying with GitLab personal access token which I checked via API http call and works.

Also I have a Kotlin exception error notification from IDE:

```
kotlin.UninitializedPropertyAccessException: lateinit property webView has not been initialized
	at com.codestream.webview.WebViewService.getWebView(WebViewService.kt:40)
	at com.codestream.webview.WebViewService.lambda$1$lambda$0(WebViewService.kt:65)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
```

Plugin is completely useless because of this bug.

I'm very disappointed that your team does not react to the review section on your IntelliJ plugin page...

**Comment by planteater** [comment]
Hi @agnieszkajanicka - The fact that you're only seeing Observability is correct. Please see the following post regarding CodeStream's new product focus. https://github.com/TeamCodeStream/codestream/issues/1742

As for the GitLab issue, I wasn't able to reproduce it on my end so I think we'll need a log file to proceed. In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can send it to me at codestream@newrelic.com. Thanks.
