### ISSUE TITLE
Error when trying to sign in to GitLab Selfhosted

### ISSUE THREAD

**Issue by gabrielshanahan** [TeamCodeStream/codestream#332]
Hello,

I am attempting to setup CodeStream for a testing run in our company. We're using a self-managed GitLab instance (GitLab Community Edition 8.15.3). I setup the integration in the standard way, but get stuck on an infinite loading loop in the "issues" section. When I click on "Open a pull request", I get the following

![image](https://user-images.githubusercontent.com/7802902/99778962-aacf8880-2b14-11eb-8965-d676ca016125.png)

I looked in the log, and it is full of similar errors:

```
2020-11-20 09:37:33,860 [ 536174]   INFO - agent.CodeStreamLanguageClient - [2020-11-20 08:37:33:860] [16d] GitLabEnterpriseProvider.getBoards
2020-11-20 09:37:33,860 [ 536174]   INFO - agent.CodeStreamLanguageClient - [2020-11-20 08:37:33:860] [16e] GitService.getRepoRemotes
2020-11-20 09:37:33,860 [ 536174]   INFO - agent.CodeStreamLanguageClient - [2020-11-20 08:37:33:860] [16e] GitService.getRepoRemotes returned [ssh://git@git.etnetera.cz:joe/sandbox.git] • 0 ms
2020-11-20 09:37:34,086 [ 536400]   INFO - agent.CodeStreamLanguageClient - [2020-11-20 08:37:34:086] GitLab Enterprise: Completed GET /projects/joe%2Fsandbox • 226 ms
2020-11-20 09:37:34,087 [ 536401]   WARN - agent.CodeStreamLanguageClient - [2020-11-20 08:37:34:086] /snapshot/dist/agent.js:0:0
FetchError: invalid json response body at https://git.etnetera.cz/users/sign_in reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at https://git.etnetera.cz/users/sign_in reason: Unexpected token < in JSON at position 0
    at /snapshot/dist/agent.js:0:0
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-20 09:37:34,300 [ 536614]   INFO - agent.CodeStreamLanguageClient - [2020-11-20 08:37:34:300] GitLab Enterprise: Completed GET /projects?min_access_level=20&with_issues_enabled=true • 213 ms
2020-11-20 09:37:34,300 [ 536614]   WARN - agent.CodeStreamLanguageClient - [2020-11-20 08:37:34:300] /snapshot/dist/agent.js:0:0
FetchError: invalid json response body at https://git.etnetera.cz/users/sign_in reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at https://git.etnetera.cz/users/sign_in reason: Unexpected token < in JSON at position 0
    at /snapshot/dist/agent.js:0:0
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-20 09:37:34,300 [ 536614]   INFO - agent.CodeStreamLanguageClient - [2020-11-20 08:37:34:300] [16d] GitLabEnterpriseProvider.getBoards completed • 440 ms
2020-11-20 09:37:34,320 [ 536634]   INFO - agent.CodeStreamLanguageClient - [2020-11-20 08:37:34:320] [16f] GitLabEnterpriseProvider.getCards
2020-11-20 09:37:35,544 [ 537858]   INFO - agent.CodeStreamLanguageClient - [2020-11-20 08:37:35:543] GitLab Enterprise: Completed GET /issues?state=opened&scope=assigned_to_me • 1223 ms
2020-11-20 09:37:35,544 [ 537858]   WARN - destream.webview.WebViewRouter - Request codestream/provider/cards failed with message: invalid json response body at https://git.etnetera.cz/users/sign_in reason: Unexpected token < in JSON at position 0
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request codestream/provider/cards failed with message: invalid json response body at https://git.etnetera.cz/users/sign_in reason: Unexpected token < in JSON at position 0
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-20 09:37:35,544 [ 537858]   WARN - agent.CodeStreamLanguageClient - [2020-11-20 08:37:35:544] [16f] GitLabEnterpriseProvider.getCards — failed • 1223 ms
FetchError: invalid json response body at https://git.etnetera.cz/users/sign_in reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at https://git.etnetera.cz/users/sign_in reason: Unexpected token < in JSON at position 0
    at /snapshot/dist/agent.js:0:0
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Any advice on what I'm doing wrong?

**Comment by planteater** [comment]
@gabrielshanahan - We have a release coming out early next week that might help your situation. Unfortunately, there's no guarantee though because your version of GL is very old (4 years). It's possible that the endpoints we need aren't even available. I'll follow up with you once the release is out so that you can try again at that point.

**Comment by planteater** [comment]
Per our conversation via support, this is potentially addressed in v10.1.0.

**Comment by herb123456** [comment]
I have the same issue.
My github version is: 12.8.1-ee

```
2021-02-13 21:58:44,228 [ 975577]   INFO - agent.CodeStreamLanguageClient - [2021-02-13 13:58:44:228] GitLab Self-Managed: Completed GET /projects/pi-backend%2Fpi-4.2 • 121 ms
2021-02-13 21:58:44,228 [ 975577]   WARN - agent.CodeStreamLanguageClient - [2021-02-13 13:58:44:228] /snapshot/dist/agent.js:0:0
FetchError: invalid json response body at http://my.gitlab.host.com/users/sign_in reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at http://my.gitlab.host.com/users/sign_in reason: Unexpected token < in JSON at position 0
    at /snapshot/dist/agent.js:0:0
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by cstryker** [comment]
@herb123456 one thing to check is take CodeStream out of the equation and just make a simple API call to your GitLab instance using curl or some other web request client, something like:

curl "http://<your_server>/api/v4/projects" -H "Content-Type: application/json" -H "PRIVATE-TOKEN: <your_api_token>"

Replace <your_server> with your GitLab server url and <your_api_token> with your API token. You should see JSON data for your GitLab projects returned in the response. If not, your url may not be correct.

The only way to edit the url at this time is to disconnect and then reconnect to the service. Go to your name at the top of CodeStream, then click "Integrations" in the menu, find your GitLab integration at the top, click "Disconnect". Then go through connecting it again and provide the correct url.

**Comment by planteater** [comment]
@herb123456 - Just to follow up on Colin's message, it seems you may have entered the URL for one of your repositories and instead of just the base URL for your GitLab instance.

**Comment by herb123456** [comment]
I checked my gitlab url and reconnected it, I got the same error message, but I can get project list using your curl command.

How can I do for the next step?

thanks for help.

**Comment by herb123456** [comment]
I connected to my Gitlab successfully, thanks.
