### ISSUE TITLE
Error when trying to pull request - GitLab Self-Managed

### ISSUE THREAD

**Issue by RiceWorld** [TeamCodeStream/codestream#337]
Hello~

An error occurs when trying to open a PR.
Doesn't it support GitLab CE?
We are using 11.6.3 (CE)

![image](https://user-images.githubusercontent.com/20451591/100049630-286bff00-2e5b-11eb-854e-b82cb0306037.png)

CodeStream Log
------------------------------------------------
[2020-11-24 07:24:26:003] [17e] GitLabEnterpriseProvider.configure
[2020-11-24 07:24:26:003] [17f] CodeStreamApiProvider.setThirdPartyProviderToken
[2020-11-24 07:24:26:004] [180] ScmManager.getRepos
[2020-11-24 07:24:26:004] [181] CodeStreamApiProvider.getMe
[2020-11-24 07:24:26:006] GIT: Running(): git log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --
[Warn  - 오후 4:24:26] [2020-11-24 07:24:26:094] Error(): C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --)
    (128) Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --
fatal: bad revision ''

fatal: bad revision ''

[Error - 오후 4:24:26] [2020-11-24 07:24:26:094] git — -c, core.quotepath=false, -c, color.ui=false, log, -M, -n1, --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e, , --,   cwd=''

  
Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --
fatal: bad revision ''

Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --
fatal: bad revision ''

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2020-11-24 07:24:26:094] GIT: Completed(): git log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  -- in 88 ms
[2020-11-24 07:24:26:817] API(c7fef458-d852-4915-9d88-7f3931e2c924): Completed GET /users/me • 812 ms
[2020-11-24 07:24:26:817] [181] CodeStreamApiProvider.getMe completed • 812 ms
[2020-11-24 07:24:26:817] [182] GitService.getRepoRemotes
[2020-11-24 07:24:26:817] [182] GitService.getRepoRemotes returned [ssh://git@192.168.168.175:eshop/member-api.git] • 0 ms
[2020-11-24 07:24:26:818] [183] GitService.getRepoRemotes
[2020-11-24 07:24:26:818] [183] GitService.getRepoRemotes returned [ssh://git@192.168.168.175:eshop/member-api.git] • 0 ms
[2020-11-24 07:24:26:818] [180] ScmManager.getRepos completed • 813 ms
[2020-11-24 07:24:26:826] API(b18a1ec2-c5ce-4755-9ce0-d9086987fbd6): Completed PUT /provider-set-token/gitlab_enterprise body={"teamId":"5fbc6c8ef3a05b18ae7b6861","token":"<hidden>","data":{"baseUrl":"http://192.168.168.175:10736"}} • 822 ms
[2020-11-24 07:24:26:826] [186] CodeStreamAgent.sendNotification(codestream/didChangeData:users)
[2020-11-24 07:24:26:826] [186] CodeStreamAgent.sendNotification(codestream/didChangeData:users) completed • 0 ms
[2020-11-24 07:24:26:826] [17f] CodeStreamApiProvider.setThirdPartyProviderToken completed • 823 ms
[2020-11-24 07:24:26:826] [187] CodeStreamSession.updateProviders
[2020-11-24 07:24:26:827] [17e] GitLabEnterpriseProvider.configure completed • 823 ms
[2020-11-24 07:24:26:827] [189] CodeStreamAgent.sendNotification(codestream/didChangeData:providers)
[2020-11-24 07:24:26:827] [189] CodeStreamAgent.sendNotification(codestream/didChangeData:providers) completed • 0 ms
[2020-11-24 07:24:26:827] [187] CodeStreamSession.updateProviders completed • 0 ms
[2020-11-24 07:24:26:829] GIT: Running(): git log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --
[2020-11-24 07:24:26:836] [18a] ScmManager.getBranches
[2020-11-24 07:24:26:836] GIT: Running(c:/Repositories/test-api/member): git branch
[2020-11-24 07:24:26:842] BROADCASTER: PUBNUB: Message received on user-5fbc51b7f3a05b18ae7b680a at 1606202666806
[2020-11-24 07:24:26:842] BROADCASTER: Broadcaster message received at: 1606202666806
[2020-11-24 07:24:26:842] BROADCASTER: _lastMessageReceivedAt updated
[2020-11-24 07:24:26:842] BROADCASTER: Broadcaster messages
[Warn  - 오후 4:24:26] [2020-11-24 07:24:26:922] Error(): C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --)
    (128) Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --
fatal: bad revision ''

fatal: bad revision ''

[Error - 오후 4:24:26] [2020-11-24 07:24:26:922] git — -c, core.quotepath=false, -c, color.ui=false, log, -M, -n1, --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e, , --,   cwd=''

  
Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --
fatal: bad revision ''

Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  --
fatal: bad revision ''

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2020-11-24 07:24:26:922] GIT: Completed(): git log -M -n1 --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e  -- in 93 ms
[2020-11-24 07:24:26:932] GIT: Completed(c:/Repositories/test-api/member): git branch in 96 ms
[2020-11-24 07:24:26:932] [18a] ScmManager.getBranches completed • 96 ms
[2020-11-24 07:24:26:935] [18f] CodeStreamApiProvider.getMe
[2020-11-24 07:24:27:529] API(0c70507a-5f00-465a-b248-ea5d63e10ed9): Completed GET /users/me • 594 ms
[2020-11-24 07:24:27:529] [18f] CodeStreamApiProvider.getMe completed • 594 ms
[2020-11-24 07:24:27:530] [190] GitService.getRepoRemotes
[2020-11-24 07:24:27:530] [190] GitService.getRepoRemotes returned [ssh://git@192.168.168.175:eshop/member-api.git] • 0 ms
[2020-11-24 07:24:27:530] [191] CodeStreamApiProvider.getMe
[2020-11-24 07:24:28:130] API(4d3dc0b4-b212-4e7c-9185-a67b4a87abe2): Completed GET /users/me • 599 ms
[2020-11-24 07:24:28:130] [191] CodeStreamApiProvider.getMe completed • 599 ms
[2020-11-24 07:24:28:147] GitLab Enterprise: FAILED(0x) GET http://192.168.168.175:10736/api/v4/user • 17 ms
[Warn  - 오후 4:24:28] [2020-11-24 07:24:28:148] undefined

**Comment by planteater** [comment]
@RiceWorld - This may have been fixed by v10.1.0 of the CodeStream extension, which was just released. It addresses issues with using older versions of GitLab.
