### ISSUE TITLE
Codemark not showing code block

### ISSUE THREAD

**Issue by plastinin** [TeamCodeStream/codestream#408]
Hello,
My code is no longer displayed in my codemarks. 
VS Code, CodeStream v. 10.6

The problem is reproduced in case with Russian characters in the file path.
The problem is not reproduced in case with Eng characters in the file path.

![image](https://user-images.githubusercontent.com/11910528/108591990-95b8fe80-737c-11eb-8579-afd63479863f.png)

Log:
`[2021-02-20 10:02:29:153] [192] ScmManager.getRangeInfo
[Error - 13:02:29] [2021-02-20 10:02:29:154] [192] ScmManager.getRangeInfo 
Error: No document could be found for Uri(file:///c:/TL/Git3/привет/мир/1.bsl)
Error: No document could be found for Uri(file:///c:/TL/Git3/привет/мир/1.bsl)
    at ScmManager.getFileRangeInfo (c:\Users\plastinin_a\.vscode\extensions\codestream.codestream-10.6.0\dist\agent.js:34:167823)
    at ScmManager.getRangeInfo (c:\Users\plastinin_a\.vscode\extensions\codestream.codestream-10.6.0\dist\agent.js:34:165184)
    at ScmManager.i.value (c:\Users\plastinin_a\.vscode\extensions\codestream.codestream-10.6.0\dist\agent.js:1:14475)
    at c:\Users\plastinin_a\.vscode\extensions\codestream.codestream-10.6.0\dist\agent.js:16:77111
    at c:\Users\plastinin_a\.vscode\extensions\codestream.codestream-10.6.0\dist\agent.js:16:78141
    at Immediate._onImmediate (c:\Users\plastinin_a\.vscode\extensions\codestream.codestream-10.6.0\dist\agent.js:16:80569)
    at processImmediate (internal/timers.js:456:21)`

**Comment by plastinin** [comment]
So, in 10.4.3 everything is fine

**Comment by planteater** [comment]
Thanks for the report @plastinin! We'll get right on this.

**Comment by planteater** [comment]
@plastinin - This has been fixed in version 10.6.1.

**Comment by plastinin** [comment]
Thank's a lot!
