### ISSUE TITLE
failed, reason: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by hannamtt** [TeamCodeStream/codestream#420]
i get this error even when i used the latest version of codestream which i see in the change log got fixed with 

> Fixes an issue with “disable strict SSL” setting not working for self-hosted services

**Comment by planteater** [comment]
@hannamtt - Can you provide a little more detail on what you were doing at the time you got that error? I recall from my email exchange with someone else from your firm that you folks use a self-signed certificate. If you haven't already you'll need to allow for that in the CodeStream settings. In VS Code go to Settings and search for CodeStream, the scroll down and check the box labelled "Codestream: Disable Strict SSL". Restart your IDE and see if that fixes things.

If you're still seeing an issue at that point, we'll probably need a log file. In VS Code, reproduce the issue and then open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. You can either post it here, or send it to me at support@codestream.com.

**Comment by hannamtt** [comment]
ive signed in already and im just trying to view my PRs, i do have disable strict SSL checked, here is the log you asked for

`[2021-03-03 21:26:09:662] getMyPullRequests providerId="github/enterprise" query="is:pr is:open review-requested:@me"
[2021-03-03 21:26:09:662] getMyPullRequests providerId="github/enterprise" query="is:pr is:open assignee:@me"
[2021-03-03 21:26:09:662] getMyPullRequests providerId="github/enterprise" query="is:pr is:open author:@me"
[Warn  - 1:26:09 PM] [2021-03-03 21:26:09:690] GitHub query caught (elapsed=27.70257806777954ms): — {"message":"request to https://********/api/graphql failed, reason: self signed certificate in certificate chain","type":"system","errno":"SELF_SIGNED_CERT_IN_CHAIN","code":"SELF_SIGNED_CERT_IN_CHAIN"}
[Error - 1:26:09 PM] [2021-03-03 21:26:09:691] getMyPullRequests
FetchError: request to https://********/api/graphql failed, reason: self signed certificate in certificate chain
FetchError: request to https://********/api/graphql failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/home/genia/.local/share/code-server/extensions/codestream.github-enterprise-10.6.1/dist/agent.js:189:21807)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[Error - 1:26:09 PM] [2021-03-03 21:26:09:691] executeMethod failed — {"method":"getMyPullRequests"}
Error: request to https://********/api/graphql failed, reason: self signed certificate in certificate chain
Error: request to https://********/api/graphql failed, reason: self signed certificate in certificate chain
    at /home/genia/.local/share/code-server/extensions/codestream.github-enterprise-10.6.1/dist/agent.js:34:243739
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GitHubEnterpriseProvider.getMyPullRequests (/home/genia/.local/share/code-server/extensions/codestream.github-enterprise-10.6.1/dist/agent.js:34:243411)
    at async ThirdPartyProviderRegistry.executeMethod (/home/genia/.local/share/code-server/extensions/codestream.github-enterprise-10.6.1/dist/agent.js:34:374960)
[Warn  - 1:26:09 PM] [2021-03-03 21:26:09:694] GitHub query caught (elapsed=31.21523094177246ms): — {"message":"request to https://********/api/graphql failed, reason: self signed certificate in certificate chain","type":"system","errno":"SELF_SIGNED_CERT_IN_CHAIN","code":"SELF_SIGNED_CERT_IN_CHAIN"}
[Warn  - 1:26:09 PM] [2021-03-03 21:26:09:695] GitHub query caught (elapsed=32.664511919021606ms): — {"message":"request to https://********/api/graphql failed, reason: self signed certificate in certificate chain","type":"system","errno":"SELF_SIGNED_CERT_IN_CHAIN","code":"SELF_SIGNED_CERT_IN_CHAIN"}
`

**Comment by cstryker** [comment]
@hannamtt can you send the entire agent log, not just the section where you see the error message? Also, would you mind sharing the url of your GitHub Enterprise connection? If you're concerned about security, you can obfuscate the details, I just need to see the basic structure.

**Comment by hannamtt** [comment]
i sent it to the support email with the issue link as the subject
