### ISSUE TITLE
When I try to view MRs, it shows 500 internal error

### ISSUE THREAD

**Issue by ftcy0118** [TeamCodeStream/codestream#459]
I got the following error. In fact, only one MR I can view for now and all others give me this internal error.

Error Loading Pull Request:
Internal server error: {"response":{"errors":[{"message":"Internal server error"}],"status":500},"request":{"query":"query GetPullRequest($fullPath: ID!, $iid: String!) { project(fullPath: $fullPath) { mergeRequest(iid: $iid) { approvedBy(first: 50) { nodes { avatarUrl name login: username } } pipelines(first: 1) { nodes { ...pipelineFragment } } assignees(last: 100) { nodes { id name login: username avatarUrl } } participants(last: 100) { nodes { id name login: username avatarUrl } } labels(last: 15) { nodes { id color title } } currentUserTodos(last: 50) { nodes { body id targetType state } } } }}fragment pipelineFragment on Pipeline { id status stages { nodes { name detailedStatus { label tooltip } } } detailedStatus { favicon icon label text tooltip }}","variables":{"fullPath":"rtwteam/backend","iid":"2849"}}}

**Comment by planteater** [comment]
Thanks for the report @ftcy0118! We're working on this issue and I'll let you know when a fix is available.

**Comment by david10sing** [comment]
I am getting the same issue with gitlab running on our own server. It's only with certain MRs. Not all.

**Comment by planteater** [comment]
@david10sing - If possible, could you reproduce the error again and then ask your GitLab admins to grab a log file? You can either post it here, or email it to me at support@codestream.com. That would allow us to determine if the issue you’re seeing is tied to the problem outlined in this GitLab issue:

https://gitlab.com/gitlab-org/gitlab/-/issues/298827

Thanks!

**Comment by sigalor** [comment]
I encountered the same error and I just sent our GitLab logs to support@codestream.com. For reference, the relevant section is:

```
==> /var/log/gitlab/gitlab-rails/production.log <==
Started POST "/api/graphql" for <redacted> at 2021-07-21 08:22:30 +0000
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"query GetPullRequest($fullPath: ID!, $iid: String!, $after: String) {\n  project(fullPath: $fullPath) {\n    name\n    mergeRequestsEnabled\n    mergeRequestsFfOnlyEnabled\n    removeSourceBranchAfterMerge\n    mergeRequest(iid: $iid) {\n      approvedBy(first: 50) {\n        nodes {\n          avatarUrl\n          name\n          login: username\n        }\n      }\n      id\n      iid\n      createdAt\n      sourceBranch\n      targetBranch\n      title\n      description\n      webUrl\n      state\n      mergedAt\n      workInProgress\n      reference\n      projectId\n      mergeWhenPipelineSucceeds\n      mergeableDiscussionsState\n      author {\n        name\n        login: username\n        avatarUrl\n      }\n      diffRefs {\n        baseSha\n        headSha\n        startSha\n      }\n      commitCount\n      project {\n        name\n        path\n        webUrl\n        fullPath\n      }\n      sourceProject {\n        name\n        path\n        webUrl\n        fullPath\n      }\n      upvotes\n      downvotes\n      milestone {\n        title\n        id\n        webPath\n        dueDate\n      }\n      subscribed\n      userDiscussionsCount\n      discussionLocked\n      forceRemoveSourceBranch\n      reviewers {\n        nodes {\n          id\n          name\n          login: username\n          avatarUrl\n        }\n      }\n      timeEstimate\n      totalTimeSpent\n      updatedAt\n      userPermissions {\n        adminMergeRequest\n        canMerge\n      }\n      discussions(first: 50, after: $after) {\n        pageInfo {\n          endCursor\n          hasNextPage\n        }\n        nodes {\n          ...discussionFragment\n        }\n      }\n    }\n  }\n}\n\nfragment discussionFragment on Discussion {\n  createdAt\n  id\n  notes {\n    nodes {\n      author {\n        name\n        login: username\n        avatarUrl\n      }\n      body\n      bodyHtml\n      createdAt\n      discussion {\n        id\n        replyId\n        createdAt\n      }\n      id\n      position {\n        x\n        y\n        newLine\n        newPath\n        oldLine\n        oldPath\n        filePath\n        diffRefs {\n          baseSha\n          headSha\n          startSha\n        }\n      }\n      project {\n        name\n      }\n      resolvable\n      resolved\n      resolvedAt\n      resolvedBy {\n        login: username\n        avatarUrl\n      }\n      system\n      systemNoteIconName\n      updatedAt\n      userPermissions {\n        adminNote\n        readNote\n        resolveNote\n        awardEmoji\n        createNote\n      }\n    }\n  }\n  replyId\n  resolvable\n  resolved\n  resolvedAt\n  resolvedBy {\n    login: username\n    avatarUrl\n  }\n}\n", "variables"=>"[FILTERED]", "graphql"=>{"query"=>"query GetPullRequest($fullPath: ID!, $iid: String!, $after: String) {\n  project(fullPath: $fullPath) {\n    name\n    mergeRequestsEnabled\n    mergeRequestsFfOnlyEnabled\n    removeSourceBranchAfterMerge\n    mergeRequest(iid: $iid) {\n      approvedBy(first: 50) {\n        nodes {\n          avatarUrl\n          name\n          login: username\n        }\n      }\n      id\n      iid\n      createdAt\n      sourceBranch\n      targetBranch\n      title\n      description\n      webUrl\n      state\n      mergedAt\n      workInProgress\n      reference\n      projectId\n      mergeWhenPipelineSucceeds\n      mergeableDiscussionsState\n      author {\n        name\n        login: username\n        avatarUrl\n      }\n      diffRefs {\n        baseSha\n        headSha\n        startSha\n      }\n      commitCount\n      project {\n        name\n        path\n        webUrl\n        fullPath\n      }\n      sourceProject {\n        name\n        path\n        webUrl\n        fullPath\n      }\n      upvotes\n      downvotes\n      milestone {\n        title\n        id\n        webPath\n        dueDate\n      }\n      subscribed\n      userDiscussionsCount\n      discussionLocked\n      forceRemoveSourceBranch\n      reviewers {\n        nodes {\n          id\n          name\n          login: username\n          avatarUrl\n        }\n      }\n      timeEstimate\n      totalTimeSpent\n      updatedAt\n      userPermissions {\n        adminMergeRequest\n        canMerge\n      }\n      discussions(first: 50, after: $after) {\n        pageInfo {\n          endCursor\n          hasNextPage\n        }\n        nodes {\n          ...discussionFragment\n        }\n      }\n    }\n  }\n}\n\nfragment discussionFragment on Discussion {\n  createdAt\n  id\n  notes {\n    nodes {\n      author {\n        name\n        login: username\n        avatarUrl\n      }\n      body\n      bodyHtml\n      createdAt\n      discussion {\n        id\n        replyId\n        createdAt\n      }\n      id\n      position {\n        x\n        y\n        newLine\n        newPath\n        oldLine\n        oldPath\n        filePath\n        diffRefs {\n          baseSha\n          headSha\n          startSha\n        }\n      }\n      project {\n        name\n      }\n      resolvable\n      resolved\n      resolvedAt\n      resolvedBy {\n        login: username\n        avatarUrl\n      }\n      system\n      systemNoteIconName\n      updatedAt\n      userPermissions {\n        adminNote\n        readNote\n        resolveNote\n        awardEmoji\n        createNote\n      }\n    }\n  }\n  replyId\n  resolvable\n  resolved\n  resolvedAt\n  resolvedBy {\n    login: username\n    avatarUrl\n  }\n}\n", "variables"=>"[FILTERED]"}}
Can't verify CSRF token authenticity.

==> /var/log/gitlab/gitaly/current <==
<redacted>

==> /var/log/gitlab/gitlab-rails/production.log <==

NoMethodError (undefined method `on_image?' for "{}":String):
  app/graphql/types/notes/diff_position_type.rb:47:in `x'
  app/graphql/types/base_field.rb:46:in `block (2 levels) in resolve_field'
  app/graphql/types/base_field.rb:35:in `block in resolve_field'
  app/graphql/types/base_field.rb:31:in `resolve_field'
  lib/gitlab/graphql/calls_gitaly/instrumentation.rb:18:in `block in instrument'
  lib/gitlab/graphql/generic_tracing.rb:40:in `with_labkit_tracing'
  lib/gitlab/graphql/generic_tracing.rb:30:in `platform_trace'
  lib/gitlab/graphql/generic_tracing.rb:40:in `with_labkit_tracing'
  lib/gitlab/graphql/generic_tracing.rb:30:in `platform_trace'
  app/graphql/gitlab_schema.rb:43:in `multiplex'
  app/graphql/gitlab_schema.rb:50:in `execute'
  app/controllers/graphql_controller.rb:75:in `execute_query'
  app/controllers/graphql_controller.rb:32:in `execute'
  app/controllers/concerns/sessionless_authentication.rb:30:in `sessionless_bypass_admin_mode!'
  app/controllers/application_controller.rb:482:in `set_current_admin'
  lib/gitlab/i18n.rb:73:in `with_locale'
  lib/gitlab/i18n.rb:79:in `with_user_locale'
  app/controllers/application_controller.rb:467:in `set_locale'
  lib/gitlab/error_tracking.rb:52:in `with_context'
  app/controllers/application_controller.rb:532:in `sentry_context'
  app/controllers/application_controller.rb:460:in `block in set_current_context'
  lib/gitlab/application_context.rb:56:in `block in use'
  lib/gitlab/application_context.rb:56:in `use'
  lib/gitlab/application_context.rb:22:in `with_context'
  app/controllers/application_controller.rb:451:in `set_current_context'
  lib/gitlab/metrics/elasticsearch_rack_middleware.rb:16:in `call'
  lib/gitlab/middleware/rails_queue_duration.rb:33:in `call'
  lib/gitlab/metrics/rack_middleware.rb:16:in `block in call'
  lib/gitlab/metrics/transaction.rb:56:in `run'
  lib/gitlab/metrics/rack_middleware.rb:16:in `call'
  lib/gitlab/request_profiler/middleware.rb:17:in `call'
  lib/gitlab/jira/middleware.rb:19:in `call'
  lib/gitlab/middleware/go.rb:20:in `call'
  lib/gitlab/etag_caching/middleware.rb:21:in `call'
  lib/gitlab/middleware/multipart.rb:172:in `call'
  lib/gitlab/middleware/read_only/controller.rb:50:in `call'
  lib/gitlab/middleware/read_only.rb:18:in `call'
  lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
  lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
  lib/gitlab/middleware/basic_health_check.rb:25:in `call'
  lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
  lib/gitlab/middleware/request_context.rb:23:in `call'
  config/initializers/fix_local_cache_middleware.rb:9:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:76:in `call'
  lib/gitlab/middleware/release_env.rb:12:in `call'

Completed 500 Internal Server Error in 529ms (Views: 0.5ms | ActiveRecord: 48.1ms | Elasticsearch: 0.0ms | Allocations: 174017)
```

**Comment by bcanzanella** [comment]
@sigalor this looks like an internal error coming directly from your GItLab instance triggered by a CodeStream query. I'd contact your GitLab admin and/or open an issue with GitLab itself since we can't do that on your behalf.

**Comment by planteater** [comment]
@sigalor - I wanted to follow up on this to see if you were still experiencing this issue, or if your GitLab admin was able to help at all.

**Comment by sigalor** [comment]
@planteater Yes, I am still experiencing the same issue with CodeStream 12.3.1. in VS Code 1.62.3 and GitLab Community Edition 14.5.0.
