### ISSUE TITLE
Support for YouTrack Standalone (on-prem)

### ISSUE THREAD

**Issue by wmalgadey** [TeamCodeStream/codestream#467]
We use youtrack as our issue management tool. But I always receive errors in vs code output:

```log
[2021-03-31 09:51:09:912] AgentConnection.sendRequest(codestream/provider/boards) — {"providerId":"youtrack*com"}
Error: Request codestream/provider/boards failed with message: invalid json response body at https://***domain***/youtrack/api/admin/projects?fields=id%2Cname%2CshortName reason: Unexpected token < in JSON at position 0
[2021-03-31 09:51:09:912] /Users/wolfgang/.vscode/extensions/codestream.codestream-10.7.2/dist/extension.js:1:12170
Error: Request codestream/provider/boards failed with message: invalid json response body at https://***domain***/youtrack/api/admin/projects?fields=id%2Cname%2CshortName reason: Unexpected token < in JSON at position 0 
```

The reason is, that our youtrack is not hosted in path `/youtrack` the api is only accessible on `/api..`.

We use Youtrack 2020.6

**Comment by wmalgadey** [comment]
```
[2021-03-31 09:51:09:912] YouTrack: Completed GET /admin/projects?fields=id%2Cname%2CshortName • 122 ms
[Error - 11:51:09 AM] [2021-03-31 09:51:09:912] [2ee] YouTrackProvider.getBoards — failed • 122 ms
FetchError: invalid json response body at https://***domain***/youtrack/api/admin/projects?fields=id%2Cname%2CshortName reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at https://***domain***/youtrack/api/admin/projects?fields=id%2Cname%2CshortName reason: Unexpected token < in JSON at position 0
    at /Users/***user***/.vscode/extensions/codestream.codestream-10.7.2/dist/agent.js:23:73788
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async YouTrackProvider.fetch (/Users/***user***/.vscode/extensions/codestream.codestream-10.7.2/dist/agent.js:34:69767)
    at async YouTrackProvider.getBoards (/Users/***user***/.vscode/extensions/codestream.codestream-10.7.2/dist/agent.js:34:326576)
```

**Comment by SaschaWeisenberger** [comment]
Same issue here, can't wait to have this integration, since it's the last thing for me that's missing. When this feature is implemented, I can do completely everything from within my IDE :)
