### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#489]
Android Studio 4.2 RC 1
Build #AI-202.7660.26.42.7231092, built on March 24, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64 

but when I set server url :http://dev-clien(***)net:12000；restart AS。
An unexpected error has occurred.

**Comment by Callanna** [comment]
Codestream is version: 11.0.1

**Comment by planteater** [comment]
@Callanna - I think this is the same issue as https://github.com/TeamCodeStream/codestream/issues/486

Does that sound right to you? We're working on a fix and hope to have something ready on Monday.

**Comment by Callanna** [comment]
I use the patch ：https://www.dropbox.com/s/zyhz73d6oc5cww7/codestream-jb-11.0.1%2B3972.zip?dl=0
but the error  is still there。
the idea log:
2021-04-12 12:16:10,966 [9129953]   WARN - agent.CodeStreamLanguageClient - [2021-04-12 04:16:10:961] pullRequestsStateHandler: Field 'currentUser' doesn't exist on type 'Query': {"response":{"errors":[{"message":"Field 'currentUser' doesn't exist on type 'Query'","locations":[{"line":3,"column":5}],"fields":["query","currentUser"]}],"status":200},"request":{"query":"\n\t\t\t{\n\t\t\t\tcurrentUser {\n\t\t\t\t\tid\n\t\t\t\t\tlogin:username\n\t\t\t\t\tname\n\t\t\t\t\tavatarUrl\n\t\t\t\t}\n\t\t\t}"}} 
2021-04-12 12:18:09,166 [9248153]   INFO - .script.IdeScriptEngineManager - javax.script.ScriptEngineManager initialized in 212 ms 
2021-04-12 12:18:10,934 [9249921]   WARN - agent.CodeStreamLanguageClient - [2021-04-12 04:18:10:933] GitLab query caught: — {"response":{"errors":[{"message":"Field 'currentUser' doesn't exist on type 'Query'","locations":[{"line":3,"column":5}],"fields":["query","currentUser"]}],"status":200},"request":{"query":"\n\t\t\t{\n\t\t\t\tcurrentUser {\n\t\t\t\t\tid\n\t\t\t\t\tlogin:username\n\t\t\t\t\tname\n\t\t\t\t\tavatarUrl\n\t\t\t\t}\n\t\t\t}"}} 
2021-04-12 12:18:10,934 [9249921]   WARN - agent.CodeStreamLanguageClient - [2021-04-12 04:18:10:933] pullRequestsStateHandler: Field 'currentUser' doesn't exist on type 'Query': {"response":{"errors":[{"message":"Field 'currentUser' doesn't exist on type 'Query'","locations":[{"line":3,"column":5}],"fields":["query","currentUser"]}],"status":200},"request":{"query":"\n\t\t\t{\n\t\t\t\tcurrentUser {\n\t\t\t\t\tid\n\t\t\t\t\tlogin:username\n\t\t\t\t\tname\n\t\t\t\t\tavatarUrl\n\t\t\t\t}\n\t\t\t}"}} 
2021-04-12 12:18:10,934 [9249921]   WARN - .codestream.agent.AgentService - (node:5001) UnhandledPromiseRejectionWarning: Error: Field 'currentUser' doesn't exist on type 'Query': {"response":{"errors":[{"message":"Field 'currentUser' doesn't exist on type 'Query'","locations":[{"line":3,"column":5}],"fields":["query","currentUser"]}],"status":200},"request":{"query":"\n\t\t\t{\n\t\t\t\tcurrentUser {\n\t\t\t\t\tid\n\t\t\t\t\tlogin:username\n\t\t\t\t\tname\n\t\t\t\t\tavatarUrl\n\t\t\t\t}\n\t\t\t}"}} 
2021-04-12 12:18:10,934 [9249921]   WARN - .codestream.agent.AgentService -     at e.<anonymous> (/snapshot/dist/agent.js:0:0) 
2021-04-12 12:18:10,935 [9249922]   WARN - .codestream.agent.AgentService -     at /snapshot/dist/agent.js:0:0 
2021-04-12 12:18:10,935 [9249922]   WARN - .codestream.agent.AgentService -     at Object.s [as next] (/snapshot/dist/agent.js:0:0) 
2021-04-12 12:18:10,935 [9249922]   WARN - .codestream.agent.AgentService -     at o (/snapshot/dist/agent.js:0:0) 
2021-04-12 12:18:10,935 [9249922]   WARN - .codestream.agent.AgentService -     at process._tickCallback (internal/process/next_tick.js:68:7) 
2021-04-12 12:18:10,935 [9249922]   WARN - .codestream.agent.AgentService - (node:5001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 77) 
2021-04-12 12:18:11,617 [9250604]   INFO - rationStore.ComponentStoreImpl - Saving Module: 'tuyasmart-device-ui.device-ui'FacetManager took 11 ms 
2021-04-12 12:18:11,738 [9250725]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=tuyasmart-device-ui, containerState=ACTIVE, componentStore=/Users/callannaduan/Documents/ProjectWork/tuyasmart-device-ui)GitToolBoxBlamePersistence took 15 ms, libraryTable took 18 ms 
2021-04-12 12:18:25,040 [9264027]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=tuyasmart-device-ui, containerState=ACTIVE, componentStore=/Users/callannaduan/Documents/ProjectWork/tuyasmart-device-ui)libraryTable took 52 ms 
2021-04-12 12:18:26,213 [9265200]   INFO - estream.webview.WebViewService - Loading WebView 
2021-04-12 12:18:28,026 [9267013]   INFO - agent.CodeStreamLanguageClient - [2021-04-12 04:18:28:025] [770] CodeStreamApiProvider.getUnreads 
2021-04-12 12:18:28,028 [9267015]   INFO - agent.CodeStreamLanguageClient - [2021-04-12 04:18:28:025] [771] CodeStreamApiProvider.getPreferences 
2021-04-12 12:18:28,028 [9267015]   INFO - agent.CodeStreamLanguageClient - [2021-04-12 04:18:28:028] [770] CodeStreamApiProvider.getUnreads completed • 2 ms 
2021-04-12 12:18:28,052 [9267039]   INFO - agent.CodeStreamLanguageClient - [2021-04-12 04:18:28:051] API(46cdee5d-a7ac-43ac-8190-16a22a9462b2): Completed GET /preferences • 25 ms 
2021-04-12 12:18:28,053 [9267040]   INFO - agent.CodeStreamLanguageClient - [2021-04-12 04:18:28:051] [771] CodeStreamApiProvider.getPreferences completed • 25 ms 
2021-04-12 12:18:28,187 [9267174]   INFO - agent.CodeStreamLanguageClient - [2021-04-12 04:18:28:186] Verifying API server connectivity 
2021-04-12 12:18:28,205 [9267192]   INFO - agent.CodeStreamLanguageClient - [2021-04-12 04:18:28:204] API server status: 200 
2021-04-12 12:18:28,206 [9267193]   INFO - agent.CodeStreamLanguageClient - [2021-04-12 04:18:28:206] [772] CodeStreamSession.verifyConnectivity completed • 19 ms

**Comment by Callanna** [comment]
[studio-logs-20210412-121844.zip](https://github.com/TeamCodeStream/codestream/files/6294041/studio-logs-20210412-121844.zip)

**Comment by planteater** [comment]
@Callanna - This has been fixed in v11.0.2 of our extension for JetBrains. It has to go through the JetBrains approval process, which usually takes 24 hours. But if you don't want to wait you can download it here:

https://www.dropbox.com/s/plb8e4pohe3p3oq/codestream-jb-jcef-11.0.2%2B140.zip?dl=0

Thanks for your patience!

**Comment by planteater** [comment]
v11.0.2 of the JetBrains extension is now available in the marketplace.
