### ISSUE TITLE
Exceptions in CodeStream plugin for webstorm

### ISSUE THREAD

**Issue by brent-jacobson** [TeamCodeStream/CodeStream#49]
Clicked on "Connect to Jira" and got
java.lang.Throwable: Error: spawn /snapshot/dist/xdg-open ENOENT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.codestream.AgentService$captureErrorStream$1.run(AgentService.kt:124)
	at java.lang.Thread.run(Thread.java:748)

Tried to send a message on slack and got
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at com.codestream.AgentService.documentMarkers(AgentService.kt:183)
	at com.codestream.editor.EditorService$updateMarkers$2.invokeSuspend(EditorService.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 8 more

**Comment by planteater** [comment]
@brent-jacobson - Thanks for the report! We've got this fixed already for our next release, which should be a little later this week.

**Comment by planteater** [comment]
@brent-jacobson - This has been fixed in version 0.52.1, which is now available.
