### ISSUE TITLE
Merge request not listed when using proxy (other parts work)

### ISSUE THREAD

**Issue by BorisTrnka** [TeamCodeStream/codestream#514]
Hello,

  I do have an issue with getting the merge request listed/updated when being behind the proxy; while the other features/parts work fine. Switching the proxy off all the features including merge requests work fine. 
  I get "Network error" message. Here the console output:

```
[2021-04-20 19:48:31:430] Webview: Received message codestream/provider/generic(wv:104:GrNz-lSQTZG8uujl1u3e-A) from the webview
[2021-04-20 19:48:31:430] AgentConnection.sendRequest(codestream/provider/generic)
[2021-04-20 19:51:10:171] AgentConnection.sendRequest(codestream/provider/generic) — {"method":"getMyPullRequests","providerId":"gitlab*com","params":{"queries":["state:opened reviewer_username:@me scope:all","state:opened scope:assigned_to_me","state:opened scope:created_by_me","recent"],"isOpen":false,"force":true}}
Error: Request codestream/provider/generic failed with message: Network error
[2021-04-20 19:51:10:171] c:\Users\XXXXXX\.vscode\extensions\codestream.codestream-11.0.3\dist\extension.js:1:12170
Error: Request codestream/provider/generic failed with message: Network error
[2021-04-20 19:51:10:172] WebviewPanel: Completed posting response(wv:104:GrNz-lSQTZG8uujl1u3e-A) to the webview

```

![image](https://user-images.githubusercontent.com/80466164/115456632-ae7e4d00-a223-11eb-982a-322a2d0dd9ff.png)

**Comment by BorisTrnka** [comment]
proxy set as:
```
    "http.proxy": "http://<IP>:8080",
    "https.proxy": "http://<IP>:8080",
    "http.proxyStrictSSL": false,
```

**Comment by cstryker** [comment]
@BorisTrnka one question ... does your `https.proxy` setting need to be set to `https://<IP>:8080` (or some other port?)

**Comment by BorisTrnka** [comment]
hi, I don't think so ... AFAIK our proxy uses http protocol and 8080 port only ...
Also, I see other https request are processed correctly.

Initialization of the extension - evidence of used proxy:
```
[2021-04-21 07:23:36:787] Initializing Sentry...
[2021-04-21 07:23:36:792] Telemetry created
[2021-04-21 07:23:36:793] Proxy support is in override with url=http://XXXXXXXXXXX:8080, strictSSL=false
[2021-04-21 07:23:36:796] Verifying API server connectivity
[2021-04-21 07:23:36:802] CodeStreamAgent.registerHandler(codestream/reporting/message)
[2021-04-21 07:23:36:802] CodeStreamAgent.registerHandler(codestream/reporting/breadcrumb)
[2021-04-21 07:23:36:802] CodeStreamAgent.registerHandler(codestream/codemarks/create)
```

Sample successful https request:
```
[2021-04-21 07:23:45:293] GIT: Completed(c:/UserData/GIT REPO/XXXXX): git rev-parse --abbrev-ref HEAD in 91 ms
[2021-04-21 07:23:45:293] [16e] GitService.getRepoRemotes — e=c:/UserData/GIT REPO/XXXXX
[2021-04-21 07:23:45:293] [16e] GitService.getRepoRemotes returned [https://gitlab.com/xxxxxxx/xxxxxx/xxxxxx.git] • 0 ms
[2021-04-21 07:23:45:293] [16b] ScmManager.getRepos completed • 92 ms
[2021-04-21 07:23:45:626] API server status: 200
[2021-04-21 07:23:45:626] [166] CodeStreamSession.verifyConnectivity completed • 547 ms — 
```

**Comment by cstryker** [comment]
OK, it might be best to experiment a bit with CodeStream itself out of the equation. Can you obtain a personal access token from GitLab with "api" scope (let me know if you don't know how to do this), then run the following curl command:

curl https://gitlab.com/api/v4/projects -H "Authorization: Bearer <Your_Access_Token>" 

That should give you a JSON of the GitLab projects you have access to. Then you can add your proxy to it with:

curl https://gitlab.com/api/v4/projects -H "Authorization: Bearer <Your_Access_Token>" --proxy <Your_Proxy_Sever>

Let me know the results.

**Comment by BorisTrnka** [comment]
Hi, with proxy option I get the JSON ... without it gets timed out ...

**Comment by cstryker** [comment]
Sorry, I should have asked you this initially - have you turned CodeStream support for proxies on? See https://docs.codestream.com/userguide/faq/proxy-support/

**Comment by BorisTrnka** [comment]
Hi, yes, proxy support is on. 
`[2021-04-21 07:23:36:793] Proxy support is in override with url=http://XXXXXXXXXXX:8080, strictSSL=false`

![image](https://user-images.githubusercontent.com/80466164/115598472-c2d15100-a2da-11eb-8069-2aedfa830dd0.png)


When proxy support is off, nothing works - neither the "feedback requests". When proxy is ON, the "Feedback requests" works, but not the "Merge requests" ...

As you can see, I tested also other providers:
![image](https://user-images.githubusercontent.com/80466164/115598384-a59c8280-a2da-11eb-873d-477b5d71d730.png)

**Comment by cstryker** [comment]
Are you trying to connect to GitLab in the cloud or your own instance of GitLab Self-Managed? If the latter, it looks like from some of your user data that you may have entered an incorrect URL.

**Comment by BorisTrnka** [comment]
You can ignore the Self-Managed ... (btw. Any idea how to remove it from the list?)

None of listed works - neither GitHub, neither Gitlab. 

E.g. I triggered refresh (Reload Query) and got these errors many times for both GitLab and GitHub calls (btw. note I clicked to reload for GitLab - started also for GitHub):
![image](https://user-images.githubusercontent.com/80466164/115612349-73dfe780-a2eb-11eb-8289-ae9dd1e287aa.png)


```
[Error - 9:39:35 PM] [2021-04-21 19:39:35:538] ClientRequest.<anonymous>
FetchError: request to https://gitlab.com/api/v4/user failed, reason: connect ETIMEDOUT 172.65.251.78:443
FetchError: request to https://gitlab.com/api/v4/user failed, reason: connect ETIMEDOUT 172.65.251.78:443
    at ClientRequest.<anonymous> (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:31:83507)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-04-21 19:39:35:538] undefined • 85515 ms
[Warn  - 9:39:35 PM] [2021-04-21 19:39:35:538] gitlab query caught: — {"message":"request to https://gitlab.com/api/v4/user failed, reason: connect ETIMEDOUT 172.65.251.78:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}
[Error - 9:39:35 PM] [2021-04-21 19:39:35:538] executeMethod failed — {"method":"getMyPullRequests"}
InternalError: Network error
InternalError: Network error
    at GitLabProvider.get (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:330494)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GitLabProvider.getCurrentUser (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:330807)
    at async GitLabProvider.getMyPullRequests (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:327220)
    at async ThirdPartyProviderRegistry.executeMethod (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:439325)
[2021-04-21 19:39:43:961] getMyPullRequests providerId="github*com" query="is:pr is:open review-requested:@me -author:@me"
[2021-04-21 19:39:43:961] getMyPullRequests providerId="github*com" query="is:pr is:open assignee:@me -author:@me"


[Warn  - 9:40:05 PM] [2021-04-21 19:40:05:006] GitHub query caught (elapsed=21045.247899994254ms): — {"message":"request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 140.82.121.6:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Network error
    at c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:252841
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GitHubProvider.getMyPullRequests (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:252513)
    at async ThirdPartyProviderRegistry.pullRequestsStateHandler (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:433744)
[Error - 9:40:05 PM] [2021-04-21 19:40:05:006] getMyPullRequests
InternalError: Network error
InternalError: Network error
    at GitHubProvider.query (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:222794)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async GitHubProvider.getMyPullRequests (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:252513)
    at async ThirdPartyProviderRegistry.pullRequestsStateHandler (c:\Users\ittrnkb\.vscode\extensions\codestream.codestream-11.0.3\dist\agent.js:42:433744)
[Warn  - 9:40:05 PM] [2021-04-21 19:40:05:006] pullRequestsStateHandler: Network error
[Warn  - 9:40:05 PM] [2021-04-21 19:40:05:010] GitHub query caught (elapsed=21049.761500000954ms): — {"message":"request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 140.82.121.6:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}
```

Performing the https request using curl with http_proxy set works just fine ...

**Comment by planteater** [comment]
@BorisTrnka - To remove GitLab Self Managed, go to the Integrations page (by clicking on your headshot at the top of the CodeStream pane), click on the GitLab Self Managed entry, and then select Disconnect.

**Comment by cstryker** [comment]
OK, I think we have a bead on this one. Will have further information tomorrow. Thanks for your patience.

**Comment by cstryker** [comment]
@BorisTrnka We think we have a fix for this which will go out with our next release. It looks like our next release will go out tomorrow, but there's a small possibility it could be delayed a bit. I'll let you know when it's available so you can try.

**Comment by cstryker** [comment]
@BorisTrnka the release is out ... please make sure you have the latest version of the CodeStream VSCode extension and try again, let me know if this fixes it.

**Comment by BorisTrnka** [comment]
@cstryker it works just like a charm (thumbs up, hat down) :)

Thanks for the prompt support!

**Comment by cstryker** [comment]
Great to hear, thanks!
