### ISSUE TITLE
VcsException:  Failed to process Git output - pipe already closed

### ISSUE THREAD

**Issue by TobseF** [TeamCodeStream/codestream#524]
When clicking "Start review" and clicking one file out of the "Merge Request"-tab the following error occurs:

```com.intellij.openapi.vcs.VcsException: Failed to process Git output: Die Pipe wird gerade geschlossen
	at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:151)
	at git4idea.history.GitDetailsCollector.readRecordsFromHandler(GitDetailsCollector.kt:95)
	at git4idea.history.GitDetailsCollector.readFullDetailsFromHandler(GitDetailsCollector.kt:70)
	at git4idea.history.GitDetailsCollector.readFullDetailsForHashes(GitDetailsCollector.kt:44)
	at git4idea.history.GitLogUtil.readFullDetailsForHashes(GitLogUtil.java:209)
	at git4idea.log.GitLogProvider.readFullDetails(GitLogProvider.java:334)
	at com.intellij.vcs.log.util.VcsLogUtil.getDetails(VcsLogUtil.java:213)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.LocalRepositoryFileService.findChanges(LocalRepositoryFileService.kt:35)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.RepositoryFileDecorator.findChanges(RepositoryFileDecorator.kt:13)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.CachedRepositoryFile.access$findChanges$s645213640(CachedRepositoryFile.kt:10)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.CachedRepositoryFile$findChanges$1.invoke(CachedRepositoryFile.kt:20)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.CachedRepositoryFile$findChanges$1.invoke(CachedRepositoryFile.kt:10)
	at net.ntworld.mergeRequest.api.Cache$DefaultImpls.getOrRun(Cache.kt:28)
	at net.ntworld.mergeRequestIntegration.provider.MemoryCache.getOrRun(MemoryCache.kt:11)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.CachedRepositoryFile.findChanges(CachedRepositoryFile.kt:18)
	at net.ntworld.mergeRequestIntegrationIde.rework.internal.ReworkWatcherImpl$myGetCommitsTaskListener$1.dataReceived(ReworkWatcherImpl.kt:78)
	at net.ntworld.mergeRequestIntegrationIde.task.GetCommitsTask.run(GetCommitsTask.kt:36)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by TobseF** [comment]
Sorry... seems to be the wrong repo
