### ISSUE TITLE
Failed to load MR list from Gitlab.com

### ISSUE THREAD

**Issue by sohan-dutta** [TeamCodeStream/codestream#701]
**Problem**
Unable to load Gitlab MR list in codestream

![image](https://user-images.githubusercontent.com/80874945/131213202-e7348256-d601-49b7-86a1-82778b32087e.png)

**StackTrace**

```
[2021-08-28 07:26:45:184] [326] GitService.getRepoRemotes returned [https://sohan3@gitlab.com/sudipta2/int-perry-benidorm.git] • 0 ms
[2021-08-28 07:26:45:184] [325] ScmManager.getRepos completed • 0 ms
[2021-08-28 07:26:45:184] [327] ThirdPartyProviderRegistry.queryThirdParty:undefined
[2021-08-28 07:26:45:184] queryThirdParty: found matching provider for gitlab.com. providerId=gitlab*com
[2021-08-28 07:26:45:184] [327] ThirdPartyProviderRegistry.queryThirdParty:undefined completed • 0 ms
[Warn  - 12:56:45 PM] [2021-08-28 07:26:45:575] handleErrorResponse:json: {
    "error": "scope does not have a valid value"
}
[2021-08-28 07:26:45:575] GitLab: FAILED(0x) GET https://gitlab.com/api/v4/projects/sudipta2%2Fint-perry-benidorm/merge_requests?scope=created_by_me%26per_page&with_labels_details=true • 389 ms
Warn  - 12:56:45 PM] [2021-08-28 07:26:45:575] gitlab query caught: — {}
[Error - 12:56:45 PM] [2021-08-28 07:26:45:575] GitLabProvider.handleErrorResponse
Error: Bad Request: scope does not have a valid value
Error: Bad Request: scope does not have a valid value
    at GitLabProvider.handleErrorResponse (/Users/codebuddy/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:72217)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GitLabProvider.fetch (/Users/codebuddy/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:71010)
    at async GitLabProvider.get (/Users/codebuddy/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:356971)
    at async Promise.all (index 3)
    at async GitLabProvider.getMyPullRequests (/Users/codebuddy/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:354704)
    at async ThirdPartyProviderRegistry.executeMethod (/Users/codebuddy/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:479689)
[Error - 12:56:45 PM] [2021-08-28 07:26:45:575] executeMethod failed — {"method":"getMyPullRequests"}
Error: Bad Request: scope does not have a valid value
Error: Bad Request: scope does not have a valid value
    at /Users/codebuddy/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:354810
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GitLabProvider.getMyPullRequests (/Users/codebuddy/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:354704)
    at async ThirdPartyProviderRegistry.executeMethod (/Users/codebuddy/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:479689)
[Warn  - 12:56:45 PM] [2021-08-28 07:26:45:576] handleErrorResponse:json: {
    "error": "state does not have a valid value"
}
[2021-08-28 07:26:45:576] GitLab: FAILED(0x) GET https://gitlab.com/api/v4/projects/sudipta2%2Fint-perry-benidorm/merge_requests?state=opened%26scope&with_labels_details=true • 391 ms
[Warn  - 12:56:45 PM] [2021-08-28 07:26:45:576] gitlab query caught: — {}
[2021-08-28 07:26:45:610] GitLab: Completed GET /projects/sudipta2%2Fint-perry-benidorm/merge_requests?state=opened&reviewer_username=sohan3&scope=all&with_labels_details=true • 425 ms
[Warn  - 12:56:46 PM] [2021-08-28 07:26:46:112] handleErrorResponse:json: {
    "error": "state does not have a valid value"
}
[2021-08-28 07:26:46:112] GitLab: FAILED(0x) GET https://gitlab.com/api/v4/projects/sudipta2%2Fint-perry-benidorm/merge_requests?state=opened%26scope&with_labels_details=true • 927 ms
[Warn  - 12:56:46 PM] [2021-08-28 07:26:46:112] gitlab query caught: — {}
[2021-08-28 07:27:40:117] getMyPullRequests providerId="github*com" query="is:pr is:open review-requested:@me -author:@me"
```

**Additional Information**

I think the problem lies with the URL query for fetching the merge requests. Currently, it is trying to query using:

```
?state=opened%26scope&with_labels_details=true
```

Here, the value of query `state` is parsed as `opened%26scope`, but I think it will be only `opened` and `%26` which is the URL encoded `&`, is causing the problem.

I did an HTTP request to `https://gitlab.com/api/v4/projects/sudipta2%2Fint-perry-benidorm/merge_requests?state=opened%26scope&with_labels_details=true `, which is throwing the error seen in the log.

But if do it at `https://gitlab.com/api/v4/projects/sudipta2%2Fint-perry-benidorm/merge_requests?state=opened&scope&with_labels_details=true `, this works.

**Comment by Baptiste-Garcin** [comment]
Same issue, same conclusion here. I am using:
- CodeStream: 11.0.13
- Gitlab self-managed: 13.12.10-ee
- Webstorm: 2021.2.1

As a workaround, I will use the custom merge_request query feature

![image](https://user-images.githubusercontent.com/12398583/131311540-88faa812-f616-4a2a-aedb-3380d5dcbfba.png)

**Comment by mochadwi** [comment]
> Same issue, same conclusion here. I am using:
> 
> * CodeStream: 11.0.13
> * Gitlab self-managed: 13.12.10-ee
> * Webstorm: 2021.2.1
> 
> Seems that other "template request" works fine. If I refresh the "wating review assign to me", I have a working list of PR

same issue, adding `project_id=1234` (e.g of our project gitlab id: 1234) works, but pulling every opened MR instead

**Comment by planteater** [comment]
We've got a fix for this coming soon. I'll let you know as soon as it's been released.

**Comment by planteater** [comment]
Fix in v11.0.14 of CodeStream's extension for JetBrains. (v11.0.15 for VSC)

**Comment by Baptiste-Garcin** [comment]
Works great thanks

**Comment by sohan-dutta** [comment]
Works now. Thanks, @planteater ✌🏼
