### ISSUE TITLE
queryThirdParty no matching provider when loading URL into Load MR from URL field.

### ISSUE THREAD

**Issue by benschac** [TeamCodeStream/codestream#707]
Hi,

I'm logged on to my team's code stream team. When trying to connect to gitlab to review an MR. I get this error:

```
[2021-09-07 19:02:31:393] GitLab: Completed GET /merge_requests?scope=created_by_me&per_page=5&with_labels_details=true • 269 ms
[2021-09-07 19:02:31:398] GitLab: Completed GET /merge_requests?state=opened&scope=assigned_to_me&with_labels_details=true • 276 ms
[2021-09-07 19:02:31:408] GitLab: Completed GET /merge_requests?state=opened&reviewer_username=benjamin.schachtersg&scope=all&with_labels_details=true • 286 ms
[2021-09-07 19:02:32:702] GitLab: Completed GET /merge_requests?state=opened&scope=created_by_me&with_labels_details=true • 1578 ms
[2021-09-07 19:02:38:242] BROADCASTER: PUBNUB: Message received on team-6011b9c53661b04f7ca78a6b at 1631041358215
[2021-09-07 19:02:38:243] BROADCASTER: Broadcaster message received at: 1631041358215
[2021-09-07 19:02:38:243] BROADCASTER: _lastMessageReceivedAt updated to 1631041358215
[2021-09-07 19:02:38:245] [22e] CodeStreamAgent.sendNotification(codestream/didChangeData:users)
[2021-09-07 19:02:38:245] [22e] CodeStreamAgent.sendNotification(codestream/didChangeData:users) completed • 0 ms
[2021-09-07 19:03:00:029] BROADCASTER: PUBNUB: Message received on team-6011b9c53661b04f7ca78a6b at 1631041379928
[2021-09-07 19:03:00:029] BROADCASTER: Broadcaster message received at: 1631041379928
[2021-09-07 19:03:00:029] BROADCASTER: _lastMessageReceivedAt updated to 1631041379928
[2021-09-07 19:03:00:031] [231] CodeStreamAgent.sendNotification(codestream/didChangeData:users)
[2021-09-07 19:03:00:031] [231] CodeStreamAgent.sendNotification(codestream/didChangeData:users) completed • 0 ms
[2021-09-07 19:03:00:158] queryThirdParty: no matching provider found for https://gitlab.stadiumgoods.com/javascript/StadiumGoods-App/-/merge_requests/530
```
vscode version: 1.60.0
```
Version: 1.60.0 (Universal)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```
codestream version: `v11.0.14`

**Comment by planteater** [comment]
@benschac - It appears that you're connected to GitLab cloud, but the URL for the MR in question seems like it might be for an MR on an instance of GitLab Self Managed. Is that correct? If so, go to the Integrations page on CodeStream (under the username menu at the top) and disconnect from GitLab, then connect to GitLab Self Managed.

**Comment by benschac** [comment]
That helped! Now I'm getting: 

```
[Warn  - 3:46:44 PM] [2021-09-07 19:46:44:132] Ignoring duplicate error — {"key":"failed to openPullRequestByUrl: Request codestream/provider/generic failed with message: Cannot read property 'mergeRequest' of null"}
[2021-09-07 19:46:56:009] queryThirdParty: found matching provider for gitlab.stadiumgoods.com. providerId=gitlab/enterprise
[2021-09-07 19:46:56:117] GitLab Self-Managed: FAILED(0x) GET https://gitlab.stadiumgoods.com/api/v4/user • 104 ms
[Warn  - 3:46:56 PM] [2021-09-07 19:46:56:117] gitlab_enterprise query caught: — {"info":{},"name":"InternalError"}
[Error - 3:46:56 PM] [2021-09-07 19:46:56:117] ensureInitialized failed for gitlab/enterprise
InternalError: Unauthorized
InternalError: Unauthorized
    at GitLabEnterpriseProvider.handleErrorResponse (/Users/benjamin.schachter/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:71595)
    at GitLabEnterpriseProvider.fetch (/Users/benjamin.schachter/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:71021)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GitLabEnterpriseProvider.get (/Users/benjamin.schachter/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:356971)
    at async GitLabEnterpriseProvider.getCurrentUser (/Users/benjamin.schachter/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:357424)
    at async GitLabEnterpriseProvider.ensureInitialized (/Users/benjamin.schachter/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:343059)
    at async GitLabEnterpriseProvider.ensureInitialized (/Users/benjamin.schachter/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:407131)
    at async ThirdPartyProviderRegistry.executeMethod (/Users/benjamin.schachter/.vscode/extensions/codestream.codestream-11.0.14/dist/agent.js:57:479560)
[Warn  - 3:46:56 PM] [2021-09-07 19:46:56:247] undefined 
[Error - 3:46:56 PM] [2021-09-07 19:46:56:247] executeMethod failed — {"method":"getPullRequestIdFromUrl"}
TypeError: Cannot read property 'mergeRequest' of null
TypeError: Cannot read property 'mergeRequest' of null
```

**Comment by bcanzanella** [comment]
Hi @benschac could you ensure that the gitlab token you're using allows access to the merge request url you are trying to view?

we can check to see if there is a permissions issue between your gitlab host and your token: 

create a gitlab token with the api scope

<img width="1117" alt="Screen Shot 2021-11-17 at 10 02 19 AM" src="https://user-images.githubusercontent.com/834948/142225659-a911d926-f53f-48fe-ab9e-4ce495ab3f3e.png">

then run this command from your terminal, replacing XXXX with your token:

`curl --header "PRIVATE-TOKEN: XXXX" "https://gitlab.stadiumgoods.com/api/v4/user"`

you should see some results. if you do, disconnect your gitlab integration with CodeStream and reconnect the integration using the token you just created.

**Comment by benschac** [comment]
Stopped using code stream. Closing.
