### ISSUE TITLE
JetBrains Rider Plugin Crash: java.lang.IllegalArgumentException: Property must not be null: uri

### ISSUE THREAD

**Issue by mwegner** [TeamCodeStream/codestream#712]
This is `JetBrains Rider 2021.2.1` on Intel `macOS 11.5.2`, `CodeStream 11.0.13+183`.

When opening a solution generated by Unity 2020/Rider, it immediately crashes before showing any IDE window at all.  The stack trace is:

```
java.lang.IllegalArgumentException: Property must not be null: uri
	at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
	at org.eclipse.lsp4j.WorkspaceFolder.<init>(WorkspaceFolder.java:42)
	at com.codestream.extensions.ProjectKt.getWorkspaceFolders(Project.kt:20)
	at com.codestream.agent.AgentService.initializationOptions(AgentService.kt:344)
	at com.codestream.agent.AgentService.getInitializeParams(AgentService.kt:318)
	at com.codestream.agent.AgentService.initAgent(AgentService.kt:138)
	at com.codestream.agent.AgentService.initAgent$default(AgentService.kt:120)
	at com.codestream.agent.AgentService$1.invokeSuspend(AgentService.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

I did click the `Report to CodeStream` button the fatal error info in Rider, so maybe more debug information got over there somewhere?  I don't have any confirmation # on that operation, though, so I'm not sure.

Other, non-Unity solutions open up okay for me.  We don't have any weirdness in this Unity solution; it's stock from whatever Unity + Rider integration are doing there.

**Comment by planteater** [comment]
@mwegner - Thanks for the report! I think we know how to address this, but a full log file would be helpful. In Rider, go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can send that to me at support@codestream.com if you'd prefer not to share it here.

**Comment by mwegner** [comment]
> @mwegner - Thanks for the report! I think we know how to address this, but a full log file would be helpful. In Rider, go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can send that to me at [support@codestream.com](mailto:support@codestream.com) if you'd prefer not to share it here.

Thanks!  I emailed the full zip just now.
