### ISSUE TITLE
Unable to load git repository because of wrong path

### ISSUE THREAD

**Issue by gl3nni3** [TeamCodeStream/CodeStream#73]
**Describe the bug**
Unable to load git repository because the path is wrong.
The path where the git is located is /home/glenn/Programming/C#/Backend/ZoneApi
But the path where codestream is trying too use git is /home/glenn/Programming

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [e.g., 0.53.1]
 - OS + version: Pop os 19.04
 - IDE + version: rider 2019.1.3

**Log Files**
`2019-07-17 12:16:08,956 | WARN  | CodeStreamLanguageClient       | [2019-07-17 10:16:08:956] Error(/home/glenn/Programming): /usr/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel)
    (128) Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

2019-07-17 12:16:08,956 | WARN  | CodeStreamLanguageClient       | [2019-07-17 10:16:08:956] git — -c, core.quotepath=false, -c, color.ui=false, rev-parse, --show-toplevel,   cwd='/home/glenn/Programming'

  
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)`

**Comment by planteater** [comment]
@gl3nni3 - I think we know what's going on here, but if you could send a log file that would be helpful. Instructions can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by planteater** [comment]
@gl3nni3 - Fixed in v1.3.3
