### ISSUE TITLE
SSL breaks in CLion and self hosted gitlab 

### ISSUE THREAD

**Issue by Kloenk** [TeamCodeStream/codestream#730]
When using a self hosted gitlab with hardened ssl (nginx), code stream is unable to do anything.
It shows the error: ` failed, reason: write EPROTO 8629868032:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1407:SSL alert number 70`

**Comment by jimmyjayp** [comment]
Hi @Kloenk . Can you upload the CodeStream agent log as well as the corresponding nginx log so I can dig a little deeper on this?  I'd also like to see what nginx configuration directives you've set.

**Comment by Kloenk** [comment]
~~~
FetchError: request to https://api.****.com/api/v4/user failed, reason: write EPROTO 8630453760:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1407:SSL alert number 70

    at ClientRequest.<anonymous> (/snapshot/dist/agent.js:0:0)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at TLSSocket.Socket._destroy (net.js:602:3) 
2021-10-04 14:58:08,282 [15297606]   INFO - agent.CodeStreamLanguageClient - [2021-10-04 12:58:08:282] undefined • 1656 ms 
2021-10-04 14:58:08,282 [15297606]   WARN - agent.CodeStreamLanguageClient - [2021-10-04 12:58:08:282] gitlab_enterprise query caught: — {"message":"request to https://api.****.com/api/v4/user failed, reason: write EPROTO 8630453760:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1407:SSL alert number 70\n","type":"system","errno":"EPROTO","code":"EPROTO"} 
2021-10-04 14:58:08,282 [15297606]   WARN - agent.CodeStreamLanguageClient - [2021-10-04 12:58:08:282] pullRequestsStateHandler: request to https://api.****.com/api/v4/user failed, reason: write EPROTO 8630453760:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1407:SSL alert number 70
~~~

nginx.conf:
~~~
http {
  ...
  ssl_protocols TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  qssl_prefer_server_ciphers off;
  ...
}

**Comment by Kloenk** [comment]
It's `CLion 2021.2.2`. I think it's java/kotlin?

**Comment by jimmyjayp** [comment]
Hi Kloenk. I know it's been a while but if you get a moment, can you please check your CodeStream agent log after you restart your IDE and look for any message that indicates which version of Node it's using?  Thanks.

**Comment by Kloenk** [comment]
It appears to be `Node.js version: v10.4.1` taken from the Clion logs. I have no nodejs installed on any system pathes. So this is most likely bundled by Codestream.

**Comment by jimmyjayp** [comment]
ok. Thx. Looking into that...

**Comment by planteater** [comment]
@Kloenk - Could I trouble you to install v12.7 of the CodeStream extension and try again? Thanks
