### ISSUE TITLE
Pubnub getting self signed certificate error

### ISSUE THREAD

**Issue by SteveRuble** [TeamCodeStream/codestream#776]
I'm on OSX. 

I'm on a VPN which injects a MITM cert. 

I have most things working correctly by wiring up the CA cert. I got some errors with the CodeStream VS Code plugin until I set `NODE_EXTRA_CA_CERTS` to include my CA cert. I also have "Disable Strict SSL" set to true in my CodeStream settings. Unfortunately it seems there is something in the `CodeStream (Agent)` that is not respecting that environment variable nor the setting. The extension seems able to connect to GitHub and sign me in to CodeStream, but then it shows "We're having problems connecting to CodeStream. Hold tight, we'll keep trying..." but it never succeeds. The agent logs look like this:

```
[2021-11-22 20:40:09:029] [199] CodeStreamApiProvider.fetchTeams
[2021-11-22 20:40:09:031] [19a] CodeStreamApiProvider.getPreferences
[2021-11-22 20:40:09:032] Subscribing to real-time events...
[2021-11-22 20:40:09:032] [19b] CodeStreamApiProvider.subscribe
[2021-11-22 20:40:09:032] [19c] CodeStreamUnreads.compute
[2021-11-22 20:40:09:032] [19d] CodeStreamApiProvider.getPreferences
[2021-11-22 20:40:09:034] [19e] BroadcasterEvents.connect
[2021-11-22 20:40:09:034] BROADCASTER: Broadcaster initializing...
[2021-11-22 20:40:09:034] BROADCASTER: PUBNUB: Connection initializing...
[2021-11-22 20:40:09:037] BROADCASTER: Request to subscribe to channels: ["user-619bfb7509920c6ad3e787b5","team-619bfbc968b0a2699d4e9001"]
[2021-11-22 20:40:09:037] BROADCASTER: Channels were added, will need a connected message
[2021-11-22 20:40:09:037] BROADCASTER: Ensuring subscription to all channels...
[2021-11-22 20:40:09:037] BROADCASTER: Unsubscribed channels are: ["user-619bfb7509920c6ad3e787b5","team-619bfbc968b0a2699d4e9001"]
[2021-11-22 20:40:09:037] BROADCASTER: Broadcaster subscribing to: ["user-619bfb7509920c6ad3e787b5","team-619bfbc968b0a2699d4e9001"]
[2021-11-22 20:40:09:037] BROADCASTER: PUBNUB: Subscribing to ["user-619bfb7509920c6ad3e787b5","team-619bfbc968b0a2699d4e9001"]
[2021-11-22 20:40:09:040] BROADCASTER: Broadcaster subscriptions timing out in 5s...
[2021-11-22 20:40:09:040] [19e] BroadcasterEvents.connect completed • 5 ms
[2021-11-22 20:40:09:040] [19b] CodeStreamApiProvider.subscribe completed • 8 ms
[2021-11-22 20:40:09:187] BROADCASTER: PUBNUB: Pubnub status received (category=PNUnknownCategory operation=PNSubscribeOperation)
[2021-11-22 20:40:09:187] BROADCASTER: PUBNUB: Subscribed channels: undefined
[2021-11-22 20:40:09:189] BROADCASTER: PUBNUB: PubNub network error: {
  error: true,
  operation: 'PNSubscribeOperation',
  errorData: Error: self signed certificate in certificate chain
      at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:467:12)
      at TLSSocket._finishInit (_tls_wrap.js:932:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN',
    response: undefined
  },
  category: 'PNUnknownCategory'
}
[2021-11-22 20:40:09:189] BROADCASTER: Ignoring network hiccup because subscriptions are already pending
[2021-11-22 20:40:09:209] API(d247faf6-2cc4-49f7-a0f5-35477c0284f9): Completed GET /preferences • 178 ms
[2021-11-22 20:40:09:210] [19a] CodeStreamApiProvider.getPreferences completed • 178 ms
[2021-11-22 20:40:09:219] API(2a5fa14c-ec80-432b-88e5-d2e428729a1b): Completed GET /preferences • 186 ms
[2021-11-22 20:40:09:219] [19d] CodeStreamApiProvider.getPreferences completed • 186 ms
[2021-11-22 20:40:09:219] [19f] CodeStreamApiProvider.fetchUnreadStreams
[2021-11-22 20:40:09:236] API(b7f3eb5e-ab47-4e55-92d7-1d6278183083): Completed GET /teams?mine • 206 ms
[2021-11-22 20:40:09:236] [199] CodeStreamApiProvider.fetchTeams completed • 206 ms
[2021-11-22 20:40:09:272] API(ea5d2619-f0e7-485b-83d9-08cc0f7121f8): Completed GET /repos?teamId=619bfbc968b0a2699d4e9001 • 245 ms
[2021-11-22 20:40:09:272] [d7] CodeStreamApiProvider.fetchRepos completed • 245 ms
```

It repeats several times and then gives up with this:

```
[2021-11-22 20:40:59:205] BROADCASTER: Ignoring network hiccup because subscriptions are already pending
[2021-11-22 20:41:04:088] BROADCASTER: Subscription timed out for: ["user-619bfb7509920c6ad3e787b5","team-619bfbc968b0a2699d4e9001"]
[2021-11-22 20:41:04:088] BROADCASTER: We are in trouble
[2021-11-22 20:41:04:088] BROADCASTER: Emitting status Trouble: ["user-619bfb7509920c6ad3e787b5","team-619bfbc968b0a2699d4e9001"]
[2021-11-22 20:41:04:088] BROADCASTER: Connection status
[2021-11-22 20:41:04:088] [1cb] CodeStreamAgent.sendNotification(codestream/didChangeConnectionStatus)
[2021-11-22 20:41:04:088] [1cb] CodeStreamAgent.sendNotification(codestream/didChangeConnectionStatus) completed • 0 ms
[2021-11-22 20:41:04:088] BROADCASTER: All subscriptions so far have failed after 10 retries, going into aborted mode...
[2021-11-22 20:41:04:088] BROADCASTER: Broadcaster unsubscribing: []
[2021-11-22 20:41:04:088] BROADCASTER: Emitting status Aborted: undefined
[2021-11-22 20:41:04:088] BROADCASTER: Connection status
[2021-11-22 20:41:09:255] BROADCASTER: PUBNUB: Server ping returned status error: true, assuming network hiccup
[2021-11-22 20:41:09:255] BROADCASTER: Ignoring network hiccup because subscriptions are already pending
```

**Comment by jimmyjayp** [comment]
Does the CA cert you setup specify the CodeStream endpoint in any way (https://api.codestream.com)?  The CodeStream agent uses a service called Pubnub whose API, at a low-level, makes https calls to their endpoints.

**Comment by SteveRuble** [comment]
The self signed CA cert is being used to create certs for everything to
enable packet inspection as part of a security policy I can't influence.
I've been able to get most things that make https requests to accept that
CA cert with various configuration settings, so I was hoping there was a
setting somewhere that could persuade this pubnub library to accept it.
There's nothing that specifically references the api.codestream.com domain
in my configurations.

**Comment by jimmyjayp** [comment]
I spoke to @cstryker about this. When the strict ssl config option is disabled the codestream LSP agent running inside VSC (a node.js process) creates https agent objectsused  making external https calls with this same option disabled. One of those objects is passed to the pubnub client API library which uses it for communication. In short, it _should_ be working.

We've seen this once or twice before and have spoken with pubnub about but nothing useful came from it.

We will continue to discuss but I don't have a suggestion off-hand. I suspect we'd need much more detail on your internal topology, how the proxy works, how it's configured, etc.. if we were going to pursue.  According to Pubnub, their node library uses the same core https agents that we pass in for all calls.

**Comment by SteveRuble** [comment]
OK, thanks for checking. I'm still seeing pubnub errors in the `CodeStream (Agent)` output, but the extension seems to be working. The "We're having problems connecting to CodeStream." message has stopped blocking the panel. I'm not sure what features will fail to work without the pubnub subscription but it doesn't seem to be blocking anything right now.

**Comment by planteater** [comment]
@SteveRuble - If PubNub isn't working, what you'll miss out on are things happening in real time. For example, if a teammate posts something you're activity feed won't automatically update without you reloading.
